#+title: ideavim

* intellij shortcuts

** Remember these Shortcuts
    Smart code completion                  : Ctrl + Shift + Space
    Search everywhere                      : Double Shift
    Show intention actions and quick-fixes : Alt + Enter
    Generate code                          : Alt + Ins
    Parameter info                         : Ctrl + P
    Extend selection                       : Ctrl + W
    Shrink selection                       : Ctrl + Shift + W
    Recent files popup                     : Ctrl + E
    Rename                                 : Shift + F6

** General
    Open corresponding tool window            : Alt + #[0-9]
    Save all                                  : Ctrl + S
    Synchronize                               : Ctrl + Alt + Y
    Toggle maximizing editor                  : Ctrl + Shift + F12
    Inspect current file with current profile : Alt + Shift + I
    Quick switch current scheme               : Ctrl + BackQuote (`)
    Open Settings dialog                      : Ctrl + Alt + S
    Open Project Structure dialog             : Ctrl + Alt + Shift + S
    Find Action                               : Ctrl + Shift + A

** Debugging
    Step over / into           : F8 / F7
    Smart step into / Step out : Shift + F7 / Shift +
    Run to cursor              : Alt + F9
    Evaluate expression        : Alt + F8
    Resume program             : F9
    Toggle breakpoint          : Ctrl + F8
    View breakpoints           : Ctrl + Shift + F8

** Search / Replace
    Search everywhere      : Double Shift
    Find                   : Ctrl + F
    Find next / previous   : F3 / Shift + F3
    Replace                : Ctrl + R
    Find in path           : Ctrl + Shift + F
    Replace in path        : Ctrl + Shift + R
    Select next occurrence : Alt + J
    Select all occurrences : Ctrl + Alt + Shift + J
    Unselect occurrence    : Alt + Shift + J

** Editing
    Basic code completion                           : Ctrl + Space
    Smart code completion                           : Ctrl + Shift + Space
    Complete statement                              : Ctrl + Shift + Enter
    Parameter info (within method call arguments)   : Ctrl + P
    Quick documentation lookup                      : Ctrl + Q
    External Doc                                    : Shift + F1
    Brief Info                                      : Ctrl + mouse
    Show descriptions of error at caret             : Ctrl + F1
    Generate code...                                : Alt + Insert
    Override methods                                : Ctrl + O
    Implement methods                               : Ctrl + I
    Surround with…                                  : Ctrl + Alt + T
    Comment / uncomment with line comment           : Ctrl + /
    Comment / uncomment with block comment          : Ctrl + Shift + /
    Extend selection                                : Ctrl + W
    Shrink selection                                : Ctrl + Shift + W
    Context info                                    : Alt + Q
    Show intention actions and quick-fixes          : Alt + Enter
    Reformat code                                   : Ctrl + Alt + L
    Optimize imports                                : Ctrl + Alt + O
    Auto-indent line(s)                             : Ctrl + Alt + I
    Indent / unindent selected lines                : Tab / Shift + Tab
    Cut current line to clipboard                   : Ctrl+X,Shift+Delete
    Copy current line to clipboard                  : Ctrl + C , Ctrl + Insert
    Paste from clipboard                            : Ctrl + V , Shift + Insert
    Paste from recent buffers...                    : Ctrl + Shift + V
    Duplicate current line                          : Ctrl + D
    Delete line at caret                            : Ctrl + Y
    Smart line join                                 : Ctrl + Shift + J
    Smart line split                                : Ctrl + Enter
    Start new line                                  : Shift + Enter
    Toggle case for word at caret or selected block : Ctrl + Shift + U
    Select till code block end / start              : Ctrl + Shift + ] / [
    Delete to word end                              : Ctrl + Delete
    Delete to word start                            : Ctrl + Backspace
    Expand / collapse code block                    : Ctrl + NumPad+ / 
    Expand all                                      : Ctrl+Shift+NumPad+
    Collapse all                                    : Ctrl+Shift+NumPad
    Close active editor tab                         : Ctrl + F4

** Refactoring
    Copy              : F5
    Move              : F6
    Safe Delete       : Alt + Delete
    Rename            : Shift + F6
    Refactor this     : Ctrl + Alt + Shift + T
    Change Signature  : Ctrl + F6
    Inline            : Ctrl + Alt + N
    Extract Method    : Ctrl + Alt + M
    Extract Variable  : Ctrl + Alt + V
    Extract Field     : Ctrl + Alt + F
    Extract Constant  : Ctrl + Alt + C
    Extract Parameter : Ctrl + Alt + P

** Navigation
    Go to class                               : Ctrl + N
    Go to file                                : Ctrl + Shift + N
    Go to symbol                              : Ctrl + Alt + Shift + N
    Go to next / previous editor tab          : Alt + Right/Left
    Go back to previous tool window           : F12
    Go to editor (from tool window)           : Esc
    Hide active or last active window         : Shift + Esc
    Go to line                                : Ctrl + G
    Recent files popup                        : Ctrl + E
    Navigate back / forward                   : Ctrl+Alt + Left/Right
    Navigate to last edit location            : Ctrl+Shift+Backspace
    Select current file or symbol in any view : Alt + F1
    Go to declaration                         : Ctrl + B , Ctrl + Click
    Go to implementation(s)                   : Ctrl + Alt + B
    Open quick definition lookup              : Ctrl + Shift + I
    Go to type declaration                    : Ctrl + Shift + B
    Go to super-method / super-class          : Ctrl + U
    Go to previous / next method              : Alt + Up/Down
    Move to code block end / start            : Ctrl + ]/[
    File structure popup                      : Ctrl + F12
    Type hierarchy                            : Ctrl + H
    Method hierarchy                          : Ctrl + Shift + H
    Call hierarchy                            : Ctrl + Alt + H
    Next / previous highlighted error         : F2 / Shift + F2
    Edit source / View source                 : F4 / Ctrl + Enter
    Show navigation bar                       : Alt + Home
    Toggle bookmark                           : F11
    Toggle bookmark with mnemonic             : Ctrl + F11
    Go to numbered bookmark                   : Ctrl + #[0-9]
    Show bookmarks                            : Shift + F11

** Compile and Run
    Make project                             : Ctrl + F9
    Compile selected file, package or module : Ctrl + Shift + F9
    Select configuration and run / debug     : Alt + Shift + F10/F9
    Run / Debug                              : Shift + F10 / F9
    Run context configuration from editor    : Ctrl + Shift + F10

** Usage Search
    Find usages / Find usages in file : Alt + F7 / Ctrl + F7
    Highlight usages in file          : Ctrl + Shift + F7
    Show usages                       : Ctrl + Alt + F7

** VCS / Local History
    Commit project to VCS   : Ctrl + K
    Update project from VCS : Ctrl + T
    Push commits            : Ctrl + Shift + K
    ‘VCS’ quick popup       : Alt + BackQuote (`)

** Live Templates

    Surround with Live Template : Ctrl + Alt + J
    Insert Live Template        : Ctrl + J

* ideavim set commands

List of Supported Set Commands
==============================

The following `:set` commands can appear in `~/.ideavimrc` or be set manually in the command mode:

    'clipboard'      'cb'       clipboard options
                                Standard clipboard options plus 
                                
                                `ideaput`  (default on)   - IdeaVim ONLY
                                enable native idea paste action for put operations
    
    'digraph'        'dg'       enable the entering of digraphs in Insert mode
    'gdefault'       'gd'       the ":substitute" flag 'g' is by default
    'history'        'hi'       number of command-lines that are remembered
    'hlsearch'       'hls'      highlight matches with the last search pattern
    'ignorecase'     'ic'       ignore case in search patterns
    'iskeyword'      'isk'      defines keywords for commands like 'w', '*', etc.
    'incsearch'      'is'       show where search pattern typed so far matches
    
    `keymodel`       `km`       String (default "continueselect,stopselect")

                 List of comma separated words, which enable special things that keys
                 can do. These values can be used:
                   startsel           Using a shifted special[1] key starts selection (either
                                      Select mode or Visual mode, depending on "key" being
                                      present in 'selectmode').
                   stopsel            Using a NOT-shifted special[1] key stops selection.
                                      Automatically enables `stopselect` and `stopvisual`
                   stopselect         Using a NOT-shifted special[1] key stops     - IdeaVim ONLY
                                      select mode and removes selection.
                   stopvisual         Using a NOT-shifted special[1] key stops     - IdeaVim ONLY
                                      visual mode and removes selection.
                   continueselect     Using a shifted arrow key doesn't       - IdeaVim ONLY
                                      start selection, but in select mode
                                      acts like startsel is enabled
                   continuevisual     Using a shifted arrow key doesn't       - IdeaVim ONLY
                                      start selection, but in visual mode
                                      acts like startsel is enabled
    
    'matchpairs'     'mps'   pairs of characters that "%" can match
    'nrformats'      'nf'    number formats recognized for CTRL-A command
    'number'         'nu'    print the line number in front of each line
    'relativenumber' 'rnu'   show the line number relative to the line with
                             the cursor
    'scroll'         'scr'   lines to scroll with CTRL-U and CTRL-D
    'scrolljump'     'sj'    minimum number of lines to scroll
    'scrolloff'      'so'    minimum number of lines above and below the cursor
    'selection'      'sel'   what type of selection to use

    `selectmode`     `slm`   String (default "")

                 This is a comma-separated list of words, which specify when to start
                 Select mode instead of Visual mode, when a selection is started.
                 Possible values:
                   mouse           when using the mouse
                   key             when using shifted special[1] keys
                   cmd             when using "v", "V", or <C-V>
                   ideaselection   when IDE sets a selection      - IdeaVim ONLY
                                   (examples: extend selection, wrap with while, etc.)

                   Deprecated values:
                   template        ~~please use `idearefactormode` option~~
                                   when starting a template       - IdeaVim ONLY
                   refactoring     ~~please use ideaselection~~
                                   same as ideaselection          - IdeaVim ONLY

    'showmode'       'smd'       message on the status line to show current mode
    'showcmd'        'sc'        show (partial) command in the status bar   [To Be Released]
    'sidescroll'     'ss'        minimum number of columns to scroll horizontally
    'sidescrolloff'  'siso'      min. number of columns to left and right of cursor
    'smartcase'      'scs'       no ignore case when pattern is uppercase
    'timeout'        'to'        use timeout for mapped key sequences
    'timeoutlen'     'tm'        timeout duration for a mapped key sequence
    'undolevels'     'ul'        maximum number of changes that can be undone
    'viminfo'        'vi'        information to remember after restart
    'visualbell'     'vb'        use visual bell instead of beeping
    'wrapscan'       'ws'        searches wrap around the end of file
    
    
    
    IdeaVim only commands:

    `ideamarks`      `ideamarks` Boolean (default true)
    
                     If true, creation of global mark will trigger creation of IDE's bookmark
                     and vice versa.
                     
    `idearefactormode` `idearefactormode` String(default "select")
    
                 Define the mode that would be enabled during
                 the refactoring (renaming, live template, introduce variable, etc)
                 
                 Use one of the following values:
                 - keep  - keep the mode that was enabled before starting a refactoring
                 - select - start refactoring in select mode
                 - visual - start refactoring in visual mode
                 
                 This option has effect if you are in normal, insert or replace mode before refactoring start.
                 Visual or select mode are not changed.
    
    
    `ideajoin`      `ideajoin` Boolean (default false)
    
                  If true, join command will be performed via IDE
                  See wiki/`ideajoin` examples

    `ideastatusbar`  `ideastatusbar` Boolean (default true)
                  DEPRECATED. Please use `ideastatusicon`
    
                  If false, IdeaVim icon won't be shown in the status bar.
                  Works only from `~/.ideavimrc` after the IDE restart.
                  
    `ideastatusicon`  `ideastatusicon` String(default "enabled")    [To Be Released]
    
                 Define the behavior of IdeaVim icon in the status bar.
                 
                 Use one of the following values:
                 - enabled - icon is shown in the status bar
                 - gray - use the gray version of the icon
                 - disabled - hide the icon
                 
                  Works only from `~/.ideavimrc` after the IDE restart.
                  
    `lookupkeys`    `lookupkeys`   List of strings
    
                  List of keys that should be processed by the IDE during the active lookup (autocompletion).
                  For example, <Tab> and <Enter> are used by the IDE to finish the lookup,
                        but <C-W> should be passed to IdeaVim.
                  Default value: 
                        "<Tab>", "<Down>", "<Up>", "<Enter>", "<Left>", "<Right>",
                        "<C-Down>", "<C-Up>", "<PageUp>", "<PageDown>",
                        "<C-J>", "<C-Q>"

    ----------
    [1] - cursor keys, <End>, <Home>, <PageUp> and <PageDown>

* ideavim action selection

EditorCompleteStatement                            <M-S-CR>
ReformatCode                                       <M-A-L> <A-F>
SurroundWith                                       <M-A-T>
SurroundWithLiveTemplate                           <M-A-J>
SmartTypeCompletion                                <C-S- >
    Completion -> smart type
ShowIntentionActions                               <A-CR> <C-CR>
InsertLiveTemplate                                 <M-J>

RecentChangedFiles                                 <M-S-E>
    RecentChanges                                      <A-S-C>
RecentFiles                                        <M-E>
Refactorings.QuickListPopupAction                  <C-T>

IntroduceConstant                                  <M-A-C>
IntroduceField                                     <M-A-F>
IntroduceParameter                                 <M-A-P>
IntroduceVariable                                  <M-A-V>

ExtractMethod                                      <M-A-M>

FileStructurePopup                                " like :Tags 

ShowNavBar                                        " pops up nav bar and select"

NewElement                                        " use to create things. contextual " 

SearchEverywhere                                  " search popul in ALL
GotoFile                                           "very useful"
GotoAction                                         "not so usefull"
GotoClass                                          very useful
GotoChangedFile                                    <M-O>
GotoDeclaration                                    <M-B> button=1 clickCount=1 modifiers=256 button=2 clickCount=1 modifiers=0
GotoImplementation                                 <M-A-B> button=1 clickCount=1 modifiers=768
GotoNextError                                      <F2>
GotoPreviousError                                  <S-F2>
GotoRelated                                        <M-C-Up>
GotoSuperMethod                                    <M-U>
GotoSymbol                                         <M-A-O>
GotoTest                                           <M-C-T>
GotoTypeDeclaration                                <M-S-B> <C-S-B> button=1 clickCount=1 modifiers=320 button=2 clickCount=1 modifiers=64
RecentChangedFiles                                 <M-S-E>
RecentChanges                                      <A-S-C>



QuickActions                                       "show some actions"
QuickImplementations                               "peek definition"
GotoImplementation                                 "go-to implementation (choose popup)"
QuickJavaDoc                                       " default K"

" WINDOW MANAGEMENT "
Console.Open                                       <M-S-F10>
ActivateChangesToolWindow                          <M-=>
ActivateDebugToolWindow                            <M-5>
ActivateFindToolWindow                             <M-7>
ActivateMessagesToolWindow                         <M-0>
ActivateProjectToolWindow                          <M-S-9>
ActivateRunToolWindow                              <M-4>
ActivateTerminalToolWindow                         <M-3>
ActivateTODOToolWindow                             <M-6>

* sangueiro vimrc


set hlsearch
set scrolloff=3
set ignorecase smartcase
set showmode
set history=1000

" easy system clipboard copy/paste
noremap <space>y "*y
noremap <space>Y "*Y
noremap <space>p "*p
noremap <space>P "*P

" easy window navigation
nnoremap <c-l> <c-w>l
nnoremap <c-j> <c-w>j
nnoremap <c-h> <c-w>h
nnoremap <c-k> <c-w>k
nnoremap <a-h> gT
nnoremap <a-l> gt
nnoremap <c-s-tab> gT
nnoremap <c-tab> gt

" clear the search buffer when hitting return
nnoremap <space><cr> :nohlsearch<cr>

" options
nnoremap cow :action EditorToggleUseSoftWraps<cr>
nnoremap col :action EditorToggleShowWhitespaces<cr>

" actions
nnoremap <space>q :action CloseContent<cr>
nnoremap <space>Q :action ReopenClosedTab<cr>
nnoremap <space>\ :action VimFilePrevious<cr>
nnoremap <space>e :action SearchEverywhere<cr>
nnoremap <space>E :action Switcher<cr>
nnoremap <space>t :action FileStructurePopup<cr>
nnoremap <space>T :action GotoSymbol<cr>
nnoremap <space>a :action GotoAction<cr>
nnoremap <space>b :action ToggleLineBreakpoint<cr>

" code navigation
nnoremap <space>] :action GotoImplementation<cr>
nnoremap <space>[ :action GotoSuperMethod<cr>
nnoremap <space>u :action FindUsages<cr>
nnoremap <space>gt :action GotoTest<cr>
nnoremap <space>k :action HighlightUsagesInFile<cr>
nnoremap \r :action RunClass<cr>
nnoremap \R :action Run<cr>
nnoremap \d :action DebugClass<cr>
nnoremap \D :action Debug<cr>
nnoremap \c :action CheckStyleCurrentFileAction<cr>

" code refactoring
nnoremap <space>rr :action RenameElement<cr>

" unimpaired mappings
nnoremap [<space> O<esc>j
nnoremap ]<space> o<esc>k
nnoremap [q :action PreviousOccurence<cr>
nnoremap ]q :action NextOccurence<cr>
nnoremap [m :action MethodUp<cr>
nnoremap ]m :action MethodDown<cr>
nnoremap [c :action VcsShowPrevChangeMarker<cr>
nnoremap ]c :action VcsShowNextChangeMarker<cr>


" built-in navigation to navigated items works better
nnoremap <c-o> :action Back<cr>
nnoremap <c-i> :action Forward<cr>
" but preserve ideavim defaults
nnoremap g<c-o> <c-o>
nnoremap g<c-i> <c-i>

" built in search looks better
nnoremap / :action Find<cr>
" but preserve ideavim search
nnoremap g/ /

* ideavim actionlist

--- Actions ---
$Copy                                              <M-C>
$Cut                                               <M-X> <S-Del>
$Delete                                            <Del> <BS> <M-BS>
$LRU                                              
$Paste                                             <M-V>
$Redo                                              <M-S-Z> <A-S-BS>
$SearchWeb                                         <A-S-G>
$SelectAll                                         <M-A>
$Undo                                              <M-Z>
About                                             
Actions.ActionsPlugin.GenerateToString            
ActivateAntBuildToolWindow                        
ActivateApplicationServersToolWindow              
ActivateChangesToolWindow                          <M-=>
ActivateDatabaseToolWindow                        
ActivateDebugToolWindow                            <M-5>
ActivateDesignerToolWindow                        
ActivateEventLogToolWindow                        
ActivateFavoritesToolWindow                       
ActivateFindToolWindow                             <M-7>
ActivateInspectionToolWindow                      
ActivateMavenProjectsToolWindow                   
ActivateMessagesToolWindow                         <M-0>
ActivateNavBar                                    
ActivatePalette	ToolWindow                        
ActivatePaletteToolWindow                         
ActivateProjectToolWindow                          <M-S-9>
ActivateRunToolWindow                              <M-4>
ActivateStructureToolWindow                       
ActivateTerminalToolWindow                         <M-3>
ActivateTODOToolWindow                             <M-6>
ActivateUIDesignerToolWindow                      
ActiveToolwindowGroup                             
Add.Email.Transport                               
Add.Embedded.Http.Transport                       
Add.Hibernate.Framework                           
Add.Ibatis.Framework                              
Add.JdkTimer                                      
Add.Jdo.Framework                                 
Add.Jms.Transport                                 
Add.OpenSymphonyTimer                             
Add.Toplink.Framework                             
Add.Webflow                                       
AddAllToFavorites                                 
AddAntBuildFile                                   
AddAsSwcLib                                       
AddAttributeAction                                
AddDataSourceFromServer                           
AddFrameworkSupport                               
AddGradleDslPluginAction                          
AddNewComponentAction                             
AddNewFavoritesList                               
AddNewMixinAction                                 
AddNewPageAction                                  
AddNewTabToTheEndMode                             
AddOptionDialogActionGroup                        
AddSourcesContentToSourceMap                      
AddSubtagAction                                   
AddToFavorites                                    
AddToFavoritesPopup                                <A-S-F>
AddToISuite                                       
AddToTestNGSuite                                  
AJ.NewAspect                                      
AJ.PushIn                                         
AlienCommitChangesDialog.AdditionalActions        
AlienPropertiesLocalDiff                          
AnalyzeActions                                    
AnalyzeJavaMenu                                   
AnalyzeMenu                                       
AnalyzeStacktraceOnError                          
Android.ConvertToNinePatch                        
Android.CreateResourceDirectory                   
Android.CreateResourcesActionGroup                
Android.Debugger.ViewBitmapAction                 
Android.EnableDdms                                
Android.GenerateSignedApk                         
Android.GenerateSourcesAction                     
Android.MainToolBarActionGroup                    
Android.MemoryMonitor                             
Android.OpenStringResourceEditor                  
Android.RunAndroidAvdManager                      
Android.RunAndroidSdkManager                      
Android.RunDdms                                   
Android.ShowLicenses                              
Android.ShowNavigationEditor                      
Android.SyncProject                               
Android.TraceViewSearch                            <M-F>
Android.UploadDatabase                            
AndroidConnectDebuggerAction                      
AndroidExtractAsIncludeAction                     
AndroidExtractStyleAction                         
AndroidFindStyleApplicationsAction                
AndroidInlineIncludeAction                        
AndroidInlineStyleReferenceAction                 
AndroidToolsGroup                                 
Annotate                                           <C-G>
AnonymousToInner                                  
AntBuildGroup                                     
AppEngine.UploadApplication                       
ApplyJavaeeStyle                                  
AppServers.ChooseArtifacts                        
AppServers.DebugServer                            
AppServers.DeployAll                              
AppServers.EditServerConfig                       
AppServers.RemoveArtifact                          <Del> <BS> <M-BS>
AppServers.RunServer                              
AppServers.StopServer                             
Arrangement.Alias.Rule.Add                        
Arrangement.Alias.Rule.Context.Menu               
Arrangement.Alias.Rule.Edit                       
Arrangement.Alias.Rule.Match.Condition.Move.Down  
Arrangement.Alias.Rule.Match.Condition.Move.Up    
Arrangement.Alias.Rule.Remove                     
Arrangement.Alias.Rule.ToolBar                    
Arrangement.Custom.Token.Rule.Edit                
Arrangement.Rule.Add                              
Arrangement.Rule.Edit                             
Arrangement.Rule.Group.Condition.Move.Down        
Arrangement.Rule.Group.Condition.Move.Up          
Arrangement.Rule.Group.Control.ToolBar            
Arrangement.Rule.Match.Condition.Move.Down        
Arrangement.Rule.Match.Condition.Move.Up          
Arrangement.Rule.Match.Control.Context.Menu       
Arrangement.Rule.Match.Control.ToolBar            
Arrangement.Rule.Remove                           
Arrangement.Rule.Section.Add                      
AssociateWithFileType                             
AutoIndentLines                                    <A-C-I>
AutoShowProcessWindow                             
AxisActions                                       
Back                                               <M-A-Left> button=4 clickCount=1 modifiers=0 <C-[>
BackgroundTasks                                   
BaseOnThisFunction                                
Bash.NewBashScript                                
Bash.REPL.Group                                   
Batch.Job.Create                                  
Bookmarks                                         
BuildArtifact                                     
BuildMenu                                         
ByteCodeViewer                                    
CallHierarchy                                      <A-C-H>
CallHierarchy.BaseOnThisType                      
CallHierarchyPopupMenu                            
CaptureCPUUsageData                               
CaptureMemorySnapShot                             
ChangeAttributeValueAction                        
ChangeCodeStyleScheme                             
ChangeColorScheme                                 
ChangeFileEncodingAction                          
ChangeInspectionProfile                           
ChangeKeymap                                      
ChangeLaf                                         
ChangeLineSeparators                              
ChangeScheme                                      
ChangeSignature                                    <M-F6>
ChangeSplitOrientation                            
ChangesView.AddUnversioned                         <M-A-A>
ChangesView.AddUnversioned.From.Dialog             <M-A-A>
ChangesView.ApplyPatch                            
ChangesView.Browse                                
ChangesView.Commit                                 <C-G>
ChangesView.CreatePatch                           
ChangesView.CreatePatchFromChanges                
ChangesView.DeleteUnversioned                     
ChangesView.DeleteUnversioned.From.Dialog         
ChangesView.Diff                                   <M-D>
ChangesView.Edit                                  
ChangesView.Ignore                                
ChangesView.Move                                  
ChangesView.NewChangeList                         
ChangesView.Refresh                               
ChangesView.RemoveChangeList                      
ChangesView.RemoveDeleted                         
ChangesView.Rename                                
ChangesView.Revert                                 <M-A-Z>
ChangesView.SetDefault                            
ChangesView.Shelve                                
ChangesViewPopupMenu                              
ChangesViewToolbar                                
ChangeTemplateDataLanguage                        
ChangeTypeSignature                                <M-S-F6>
ChangeView                                        
CheckForUpdate                                    
CheckinFiles                                      
CheckinProject                                    
CheckStatusForFiles                               
ChooseActiveBuildConfiguration                    
ChooseDebugConfiguration                           <A-C-D>
ChooseNextSubsequentPropertyValueEditorAction      <C-Down>
ChoosePrevSubsequentPropertyValueEditorAction      <C-Up>
ChooseRunConfiguration                             <A-C-R>
ClassNameCompletion                                <A-C- >
ClassTemplateNavigation                            <M-S-G>
CleanGradleProject                                
ClearCase.Add                                     
ClearCase.CheckOut                                
ClearCase.DeliverActivities                       
ClearCase.FindProjectCheckouts                    
ClearCase.Hijack                                  
ClearCase.Merge                                   
ClearCase.MergeProject                            
ClearCase.Properties                              
ClearCase.RebaseProject                           
ClearCase.SynchronizeWithActivities               
ClearCase.UndoCheckOut                            
ClearCase.Update                                  
ClearCase.VersionTree                             
ClearCaseFile                                     
ClearCaseProject                                  
CloseActiveTab                                     <C-S-F4>
CloseAllEditors                                   
CloseAllEditorsButActive                          
CloseAllUnmodifiedEditors                         
CloseAllUnpinnedEditors                           
CloseContent                                       <M-W>
CloseEditor                                       
CloseEditorsGroup                                 
CloseProject                                      
CodeCleanup                                       
CodeCompletion                                     <C- >
CodeCompletionGroup                               
CodeEditorBaseGroup                               
CodeEditorViewGroup                               
CodeFormatGroup                                   
CodeInsightEditorActions                          
CodeInspection.OnEditor                            <A-S-I>
CodeMenu                                          
CollapseAll                                        <M-m> <M-->
CollapseAllRegions                                 <M-S-m> <M-S-->
CollapseBlock                                      <M-S-.>
CollapseDocComments                               
CollapseRegion                                     <M-m> <M-->
CollapseRegionRecursively                          <M-A-m> <M-A-->
CollapseSelection                                  <M-.>
CollapseTreeNode                                   <m>
com.ansorgit.plugins.bash.actions.AddReplAction   
com.intellij.execution.testframework.sm.runner.ui.statistics.ShowStatisticsAction
com.intellij.execution.testframework.sm.runner.ui.statistics.ShowTestProxy
com.intellij.play.console.RunPlayConsoleAction    
com.intellij.spellchecker.actions.SpellingPopupActionGroup
com.intellij.sql.refactoring.SqlExtractNamedQueryAction
com.jetbrains.php.framework.FrameworkRunConsoleAction <M-S-X>
com.jetbrains.plugins.remotesdk.console.RunSshConsoleAction <C-Z>
CombinePropertiesFilesAction                      
CommanderPopupMenu                                
CommentByBlockComment                              <M-A-/> <M-A-o> <C-S-/> <C-S-o>
CommentByLineComment                               <M-/> <M-o>
CommentGroup                                      
CommittedChanges.Clear                            
CommittedChanges.Details                          
CommittedChanges.Filter                           
CommittedChanges.Refresh                          
CommittedChanges.Revert                           
CommittedChangesToolbar                           
Compare.LastVersion                                <C-Z>
Compare.SameVersion                               
Compare.Selected                                  
Compare.Specified                                 
CompareActions                                    
CompareClipboardWithSelection                     
CompareDirs                                       
CompareFileWithEditor                             
CompareTwoFiles                                   
Compile                                            <M-S-F9>
CompileCoffeeScript                               
CompileDirty                                       <M-F9>
CompileEcmaScript6                                
CompileProject                                    
CompilerErrorViewPopupMenu                        
ConfigureCvsRoots                                 
Console.Dialect.SpecificGroup                     
Console.EditorTableResult.Group                   
Console.Execute                                    <CR>
Console.Execute.Multiline                          <M-CR>
Console.History.Browse                             <M-A-E>
Console.History.Next                              
Console.History.Previous                          
Console.HistoryActions                            
Console.Jdbc.Close                                 <C-S-F4>
Console.Jdbc.Execute                               <M-CR>
Console.Jdbc.Execute.Selection                    
Console.Jdbc.ExplainPlan                          
Console.Jdbc.ExplainPlan.Raw                      
Console.Jdbc.Terminate                             <M-F2>
Console.JdbcActions                               
Console.Jpa.Close                                  <C-S-F4>
Console.Jpa.Execute                                <M-CR>
Console.Jpa.GenerateDDL                            <M-A-S-CR>
Console.Jpa.GenerateSql                            <M-S-CR>
Console.Jpa.Terminate                              <M-F2>
Console.JpaActions                                
Console.Open                                       <M-S-F10>
Console.Oracle.DbmsOutput                          <M-F8>
Console.SplitLine                                 
Console.TableResult.AddColumn                      <M-S-8>
Console.TableResult.AddRow                         <M-N>
Console.TableResult.Cancel                         <M-F2>
Console.TableResult.CellEditor.Popup              
Console.TableResult.ChangeCellEditorFileEncoding  
Console.TableResult.ChangeCellEditorLanguage      
Console.TableResult.ChangeColumnLanguage          
Console.TableResult.ChooseExtractor               
Console.TableResult.CloneColumn                    <M-A-S-D>
Console.TableResult.CloneRow                       <M-S-D>
Console.TableResult.ColumnActions                 
Console.TableResult.ColumnHeaderPopup             
Console.TableResult.ColumnsList                    <M-F12>
Console.TableResult.ColumnSortAsc                  <A-S-Up>
Console.TableResult.ColumnSortDesc                 <A-S-Down>
Console.TableResult.ColumnSortingActions          
Console.TableResult.ColumnSortReset                <M-A-S-BS>
Console.TableResult.ColumnVisibility               < >
Console.TableResult.CompareWith                   
Console.TableResult.Copy.ChooseExtractorGroup     
Console.TableResult.Copy.ClipboardGroup           
Console.TableResult.Copy.FileGroup                
Console.TableResult.Copy.Settings                 
Console.TableResult.CopyGroup                     
Console.TableResult.CountRows                     
Console.TableResult.Csv.PopupGroup                
Console.TableResult.DeleteColumns                  <A-S-Del>
Console.TableResult.DeleteRows                     <M-BS>
Console.TableResult.EditValue                      <F2> <CR> <A-CR>
Console.TableResult.EditValueMaximized             <S-CR> <A-S-CR>
Console.TableResult.Filter.Custom                 
Console.TableResult.FirstPage                     
Console.TableResult.Group                         
Console.TableResult.Group.Secondary               
Console.TableResult.HideColumn                    
Console.TableResult.LastPage                      
Console.TableResult.LoadFile                      
Console.TableResult.MaximizeEditingCell            <M-A-S-M>
Console.TableResult.NavigateAction                 <M-Down> <F4>
Console.TableResult.NavigateExportedAction         <A-F7> <C-F>
Console.TableResult.NavigateForeignAction          <M-B> button=1 clickCount=1 modifiers=256 button=2 clickCount=1 modifiers=0
Console.TableResult.NavigationAndEditing.Group    
Console.TableResult.NextPage                       <M-A-Down>
Console.TableResult.Options                       
Console.TableResult.Pin                           
Console.TableResult.PopupGroup                    
Console.TableResult.PreviousPage                   <M-A-Up>
Console.TableResult.Reload                         <F5>
Console.TableResult.RenameTab                     
Console.TableResult.ResetView                     
Console.TableResult.SaveLobAs                     
Console.TableResult.SetDefault                     <M-A-D>
Console.TableResult.SetNull                        <M-A-N>
Console.TableResult.ShowQuery                     
Console.TableResult.SortToggle                    
Console.TableResult.SubmitAddedRow                 <M-CR>
Console.TableResult.ToggleFilters                 
Console.TableResult.Transpose                     
Console.TabPopupGroup                             
Console.Transaction                               
Console.Transaction.Autocommit                    
Console.Transaction.Commit                        
Console.Transaction.Rollback                      
ConsoleEditorPopupMenu                            
ConsoleView.ClearAll                              
ConsoleView.FoldLinesLikeThis                     
ConsoleView.PopupMenu                             
ConsoleView.ShowAsJsonAction                      
context.clear                                      <A-S-X>
context.load                                      
context.save                                      
ContextHelp                                       
ConvertContentsToAttributeAction                  
ConvertGroovyToJava                               
ConvertIndentsGroup                               
ConvertIndentsToSpaces                            
ConvertIndentsToTabs                              
ConvertSchemaAction                               
ConvertToInstanceMethod                           
ConvertToMacLineSeparators                        
ConvertToUnixLineSeparators                       
ConvertToWindowsLineSeparators                    
CopyAsPlainText                                   
CopyAsRichText                                    
CopyElement                                        <F5>
CopyPaths                                          <M-S-C>
CopyReference                                      <M-A-S-C>
CopyUrl                                           
Coverage                                           <C-C>
CoverageMenu                                      
Create.CDI.Beans.Xml.File                         
CreateBeanManagedEntityBeanAction                 
CreateCMPField                                    
CreateContainerManagedEntityBeanAction            
CreateDesktopEntry                                
CreateEJBInterceptor                              
CreateEJBRelationship                             
CreateFilterAction                                
CreateJavaeeWebPageAction                         
CreateLauncherScript                              
CreateLibraryFromFile                             
CreateListenerAction                              
CreateMessageBean                                 
CreateResourceBundle                              
CreateRunConfiguration                            
CreateServletAction                               
CreateSingletonBean                               
CreateStatefulBean                                
CreateStatelessBean                               
CreateTaglibFileAction                            
CreateTransferObject                              
CreateWebProject                                  
CutCopyPasteGroup                                 
Cvs.Add                                           
Cvs.BrowseCVSRepository                           
Cvs.Checkout                                      
Cvs.CreateBranch                                  
Cvs.CreateTag                                     
Cvs.DeleteTag                                     
Cvs.Edit                                          
Cvs.Editors                                       
Cvs.GetFromRepository                             
Cvs.Ignore                                        
Cvs.Import                                        
Cvs.MergeAction                                   
Cvs.ToggleOffline                                 
Cvs.UndoAdd                                       
Cvs.Unedit                                        
Cvs.WatchAdd                                      
Cvs.Watchers                                      
Cvs.WatchOff                                      
Cvs.WatchOn                                       
Cvs.WatchRemove                                   
CvsActions                                        
CvsFilePopupGroup                                 
CvsGlobalGroup                                    
Database.OpenDbStorageAction                       <M-Down> <F4>
Database.Settings                                 
DatabaseView.AddActionGroup                       
DatabaseView.AddActionGroupPopup                  
DatabaseView.AddDataSourceFromUrl                 
DatabaseView.AddDataSourcesGroup                  
DatabaseView.AssignColor                          
DatabaseView.ChangeSignature                       <M-F6>
DatabaseView.CloseConnectionAction                 <M-F2>
DatabaseView.CopyAction                            <M-S-D>
DatabaseView.Ddl.AddColumn                        
DatabaseView.Ddl.AddForeignKey                    
DatabaseView.Ddl.AddIndex                         
DatabaseView.Ddl.AddPrimaryKey                    
DatabaseView.Ddl.AddTable                         
DatabaseView.DropAction                            <A-CR> <C-CR>
DatabaseView.Dump.FileGroup                       
DatabaseView.GenerateDDLAction                     <M-S-C>
DatabaseView.ImportDataSources                    
DatabaseView.PropertiesAction                      <M-I>
DatabaseView.ShowDiff                             
DatabaseView.SynchronizeAction                     <M-A-Y>
DatabaseViewPopupMenu                             
DatabaseViewToolbar                               
Debug                                              <A-D>
DebugClass                                         <A-S-D>
Debugger.AddSteppingFilter                        
Debugger.AddToWatch                               
Debugger.AdjustArrayRange                         
Debugger.AutoRenderer                             
Debugger.CustomizeContextView                     
Debugger.CustomizeThreadsView                     
Debugger.EditFrameSource                          
Debugger.EditNodeSource                           
Debugger.EditTypeSource                            <S-F4>
Debugger.EvaluateInConsole                        
Debugger.EvaluationDialogPopup                    
Debugger.FocusOnBreakpoint                        
Debugger.FramePanelPopup                          
Debugger.FreezeThread                             
Debugger.InspectPanelPopup                        
Debugger.InterruptThread                          
Debugger.MarkObject                               
Debugger.PopFrame                                 
Debugger.Representation                           
Debugger.ResumeThread                             
Debugger.ShowLibraryFrames                        
Debugger.ShowReferring                            
Debugger.ThreadsPanelPopup                        
Debugger.Tree.AddToWatches                        
Debugger.Tree.EvaluateInConsole                   
Debugger.ViewAsGroup                              
Debugger.ViewText                                 
Debugger.WatchesPanelPopup                        
DebuggerActions                                   
DebugMainMenu                                     
DecrementWindowHeight                              <M-S-Up>
DecrementWindowWidth                               <M-S-Left>
DelegateMethods                                   
DeleteAttributeAction                             
DeleteTagAction                                   
Diagram.DeselectAll                                <M-A-A>
Diagram.SelectAll                                  <M-A>
Diff.EditorPopupMenu                              
Diff.FocusOppositePane                             <M-Tab>
Diff.FocusOppositePaneAndScroll                    <M-S-Tab>
Diff.HighlightMode                                
Diff.IgnoreWhitespace                             
Diff.KeymapGroup                                   <C-Z>
Diff.NextChange                                    <M-S-]> <C-Right>
Diff.PrevChange                                    <M-S-[> <C-Left>
Diff.SelectedChange                                <M-O>
Diff.ShowDiff                                      <M-D>
Diff.ShowInExternalTool                           
Diff.ShowSettingsPopup                             <M-S-D>
Diff.UpdatedFiles                                  <M-D>
DiffPanel.Toolbar                                 
DirDiffMenu                                       
DirDiffMenu.Deployment.MirrorToLeft               
DirDiffMenu.Deployment.MirrorToRight              
DirDiffMenu.EnableEqual                           
DirDiffMenu.EnableLeft                            
DirDiffMenu.EnableNotEqual                        
DirDiffMenu.EnableRight                           
DirDiffMenu.SetCopyToLeft                         
DirDiffMenu.SetCopyToRight                        
DirDiffMenu.SetDefault                            
DirDiffMenu.SetDelete                             
DirDiffMenu.SetNoOperation                        
DirDiffMenu.WarnOnDeletion                        
DissociateResourceBundleAction                    
dmServer.manage.server.libraries                  
Document2XSD                                      
DomCollectionControl                              
DomCollectionControl.Add                           <Ins>
DomCollectionControl.Edit                          <M-Down> <F4>
DomCollectionControl.Remove                        <Del> <BS> <M-BS>
DomElementsTreeView.AddElement                     <Ins>
DomElementsTreeView.AddElementGroup               
DomElementsTreeView.DeleteElement                  <Del> <BS> <M-BS>
DomElementsTreeView.GotoDomElementDeclarationAction <M-Down> <F4>
DomElementsTreeView.TreePopup                     
Drools.CreateRuleFile                             
DSM.Analyze                                       
DSM.Close                                          <C-S-F4>
DSM.DiggIntoDependenciesAction                    
DSM.GoToNextCycle                                  <F2>
DSM.LimitDependencies                             
DSM.OpenDependencies                              
DSM.OpenInEditor                                   <M-Down> <F4>
DSM.Popup                                         
DSM.ToggleCycles                                  
DSM.ToggleFlattenPackages                         
DSM.ToggleGradient                                
DSM.ToggleModuleGroups                            
DSM.ToggleModules                                 
DSM.TogglenPackages                               
DSM.Toolbar                                       
DumpLookupElementWeights                           <M-A-S-W>
DumpSpringConfiguration                           
DumpThreads                                       
DuplicatesForm.SendToLeft                          <M-1>
DuplicatesForm.SendToRight                         <M-2>
DupLocate                                         
Dvcs.Log.ContextMenu                              
Dvcs.Log.Toolbar                                  
EditAndWatch                                      
EditBookmarksGroup                                
EditBreakpoint                                     <M-S-F8>
EditCommitMessage                                 
EditCreateDeleteGroup                             
EditEntityListenerBindingsAction                  
EditFavorites                                     
EditInterceptorBindingsAction                     
EditMacros                                        
EditMenu                                          
Editor.JSLibrariesMenu                            
Editor.JSLibrariesMenu.LibraryList                
EditorActions                                     
EditorAddOrRemoveCaret                             button=1 clickCount=1 modifiers=576
EditorAddRectangularSelectionOnMouseDrag           button=1 clickCount=1 modifiers=832
EditorBackSpace                                    <BS> <S-BS>
EditorChooseLookupItem                             <CR>
EditorChooseLookupItemCompleteStatement            <M-S-CR>
EditorChooseLookupItemDot                          <C-.>
EditorChooseLookupItemReplace                      <Tab>
EditorCloneCaretAbove                             
EditorCloneCaretBelow                             
EditorCodeBlockEnd                                 <M-A-]>
EditorCodeBlockEndWithSelection                    <M-A-S-]>
EditorCodeBlockStart                               <M-A-[>
EditorCodeBlockStartWithSelection                  <M-A-S-[>
EditorCompleteStatement                            <M-S-CR>
EditorContextBarMenu                              
EditorContextInfo                                  <C-S-Q>
EditorCopy                                         <M-C>
EditorCreateRectangularSelection                   button=2 clickCount=1 modifiers=576
EditorCut                                          <M-X> <S-Del>
EditorCutLineBackward                             
EditorCutLineEnd                                   <C-K>
EditorDecreaseFontSize                            
EditorDelete                                       <Del>
EditorDeleteLine                                   <M-BS>
EditorDeleteToLineEnd                             
EditorDeleteToLineStart                           
EditorDeleteToWordEnd                              <A-Del>
EditorDeleteToWordEndInDifferentHumpsMode         
EditorDeleteToWordStart                            <A-BS>
EditorDeleteToWordStartInDifferentHumpsMode       
EditorDown                                         <Down>
EditorDownWithSelection                            <S-Down>
EditorDuplicate                                    <M-S-D>
EditorDuplicateLines                              
EditorEnter                                        <CR>
EditorEscape                                       <Esc>
EditorGutterPopupMenu                             
EditorGutterVcsPopupMenu                          
EditorHungryBackSpace                             
EditorIncreaseFontSize                            
EditorIndentLineOrSelection                       
EditorIndentSelection                              <Tab>
EditorJoinLines                                    <C-S-J>
EditorKillRegion                                  
EditorKillRingSave                                
EditorKillToWordEnd                               
EditorKillToWordStart                             
EditorLangPopupMenu                               
EditorLeft                                         <Left>
EditorLeftWithSelection                            <S-Left>
EditorLineEnd                                      <M-Right> <C-S-E>
EditorLineEndWithSelection                         <S-End> <M-S-Right>
EditorLineStart                                    <M-Left> <C-S-A>
EditorLineStartWithSelection                       <S-Home> <M-S-Left>
EditorLookupDown                                   <C-Down>
EditorLookupUp                                     <C-Up>
EditorMatchBrace                                  
EditorMoveDownAndScroll                           
EditorMoveDownAndScrollWithSelection              
EditorMoveToPageBottom                             <M-Pagedown>
EditorMoveToPageBottomWithSelection                <M-S-Pagedown>
EditorMoveToPageTop                                <M-Pageup>
EditorMoveToPageTopWithSelection                   <M-S-Pageup>
EditorMoveUpAndScroll                             
EditorMoveUpAndScrollWithSelection                
EditorNextWord                                     <A-Right>
EditorNextWordInDifferentHumpsMode                
EditorNextWordInDifferentHumpsModeWithSelection   
EditorNextWordWithSelection                        <A-S-Right>
EditorPageDown                                     <Pagedown> <End>
EditorPageDownWithSelection                        <S-Pagedown>
EditorPageUp                                       <Pageup> <Home>
EditorPageUpWithSelection                          <S-Pageup>
EditorPaste                                        <M-V>
EditorPasteFromX11                                 button=2 clickCount=1 modifiers=0
EditorPasteSimple                                  <M-A-S-V>
EditorPopupMenu                                   
EditorPopupMenu.GoTo                              
EditorPopupMenu.Run                               
EditorPopupMenu1                                  
EditorPopupMenuDebug                              
EditorPopupMenuDebugJava                          
EditorPreviousWord                                 <A-Left>
EditorPreviousWordInDifferentHumpsMode            
EditorPreviousWordInDifferentHumpsModeWithSelection
EditorPreviousWordWithSelection                    <A-S-Left>
EditorResetFontSize                               
EditorRight                                        <Right>
EditorRightWithSelection                           <S-Right>
EditorScrollBottom                                
EditorScrollDown                                  
EditorScrollDownAndMove                           
EditorScrollLeft                                  
EditorScrollRight                                 
EditorScrollToCenter                              
EditorScrollTop                                   
EditorScrollUp                                    
EditorScrollUpAndMove                             
EditorSelectLine                                   <M-A-W> <M-L>
EditorSelectWord                                   <A-Up> <M-Þ>
EditorSplitLine                                    <M-CR>
EditorStartNewLine                                 <S-CR>
EditorStartNewLineBefore                           <M-A-CR>
EditorSwapSelectionBoundaries                     
EditorTab                                          <Tab>
EditorTabCompileGroup                             
EditorTabPopupMenu                                
EditorTabPopupMenuEx                              
EditorTabsGroup                                   
EditorTextEnd                                      <M-End>
EditorTextEndWithSelection                         <M-S-End>
EditorTextStart                                    <M-Home>
EditorTextStartWithSelection                       <M-S-Home>
EditorToggleActions                               
EditorToggleCase                                   <M-S-U>
EditorToggleColumnMode                             <M-S-8>
EditorToggleInsertState                           
EditorToggleShowIndentLines                       
EditorToggleShowLineNumbers                       
EditorToggleShowWhitespaces                       
EditorToggleStickySelection                       
EditorToggleUseSoftWraps                          
EditorUnindentSelection                            <S-Tab>
EditorUnSelectWord                                 <A-Down> <M-S-Þ>
EditorUp                                           <Up>
EditorUpWithSelection                              <S-Up>
editRunConfigurations                             
EditSelectGroup                                   
EditSelectWordGroup                               
EditSmartGroup                                    
EditSource                                         <M-Down> <F4>
EditSourceInNewWindow                              <S-F4>
EmacsStyleIndent                                  
Emmet                                             
EmmetNextEditPoint                                 <A-C-Right>
EmmetPreview                                      
EmmetPreviousEditPoint                             <A-C-Left>
EmmetUpdateTag                                    
EncapsulateFields                                 
EvaluateExpression                                 <A-F8>
ExcludeFromStubGeneration                         
excludeFromSuite                                  
excludeFromTestNGSuite                            
ExcludeFromValidation                             
Exit                                               <M-Q>
ExpandAll                                          <M-k> <M-]>
ExpandAllRegions                                   <M-]>
ExpandAllToLevel                                  
ExpandAllToLevel1                                  <M-A-j> <M-A-j>
ExpandAllToLevel2                                  <M-A-j> <M-A-j>
ExpandAllToLevel3                                  <M-A-j> <M-A-j>
ExpandAllToLevel4                                  <M-A-j> <M-A-j>
ExpandAllToLevel5                                  <M-A-j> <M-A-j>
ExpandDocComments                                 
ExpandLiveTemplateByTab                            <Tab>
ExpandLiveTemplateCustom                          
ExpandRegion                                       <M-k> <M-S-=>
ExpandRegionRecursively                            <M-A-k> <M-A-=>
ExpandToLevel                                     
ExpandToLevel1                                     <M-j> <M-j>
ExpandToLevel2                                     <M-j> <M-j>
ExpandToLevel3                                     <M-j> <M-j>
ExpandToLevel4                                     <M-j> <M-j>
ExpandToLevel5                                     <M-j> <M-j>
ExpandTreeNode                                     <k>
ExportImportGroup                                 
ExportSettings                                    
ExportTestResults                                 
ExportThreads                                     
ExportToEclipse                                   
ExportToHTML                                      
ExportToTextFile                                   <C-O>
ExpressionTypeInfo                                 <C-S-P>
ExternalJavaDoc                                    <S-F1>
ExternalSystem.AfterCompile                       
ExternalSystem.AfterRebuild                       
ExternalSystem.AfterSync                          
ExternalSystem.AssignRunConfigurationShortcut     
ExternalSystem.AssignShortcut                     
ExternalSystem.AttachProject                      
ExternalSystem.BeforeCompile                      
ExternalSystem.BeforeRebuild                      
ExternalSystem.BeforeRun                          
ExternalSystem.BeforeSync                         
ExternalSystem.CollapseAll                         <M-m> <M-->
ExternalSystem.DetachProject                       <Del> <BS> <M-BS>
ExternalSystem.EditRunConfiguration               
ExternalSystem.ExpandAll                           <M-k> <M-]>
ExternalSystem.GroupTasks                         
ExternalSystem.OpenConfig                          <M-Down> <F4>
ExternalSystem.OpenTasksActivationManager         
ExternalSystem.RefreshAllProjects                 
ExternalSystem.RefreshProject                     
ExternalSystem.RemoveRunConfiguration             
ExternalSystem.RunTask                            
ExternalSystem.ShowInheritedTasks                 
ExternalSystem.ShowSettings                       
ExternalSystem.ToggleAutoImport                   
ExternalSystemView.ActionsToolbar                 
ExternalSystemView.ActionsToolbar.CenterPanel     
ExternalSystemView.ActionsToolbar.LeftPanel       
ExternalSystemView.ActionsToolbar.RightPanel      
ExternalSystemView.BaseProjectMenu                
ExternalSystemView.ProjectMenu                    
ExternalSystemView.RunConfigurationMenu           
ExternalSystemView.TaskActivationGroup            
ExternalSystemView.TaskMenu                       
ExternalToolsGroup                                
ExtractClass                                      
ExtractInclude                                    
ExtractInterface                                  
ExtractJspTagAction                               
ExtractMethod                                      <M-A-M>
ExtractModule                                     
ExtractSuperclass                                 
Faces.CreateFacesConfigAction                     
Faces.CreateJsfAction                             
Faces.Generate.From.Persistence                   
Faces.MainGraphPopup                              
Faces.MainPageGraphPopup                          
Faces.MainPageTreePopup                           
Faces.Navigation.Graph.PageTree.GotoDeclarationAction
Faces.Navigation.Graph.PageTree.GotoSourceAction  
Faces.User.Defined.Faces.Config                   
FavoritesViewPopupMenu                            
FileChooser                                       
FileChooser.Delete                                
FileChooser.GotoDesktop                            <M-D>
FileChooser.GotoHome                               <M-1>
FileChooser.GotoJDK                               
FileChooser.GotoModule                             <M-3>
FileChooser.GotoProject                            <M-2>
FileChooser.NewFile                               
FileChooser.NewFolder                              <M-N>
FileChooser.Refresh                               
FileChooser.ShowHiddens                           
FileChooser.TogglePathShowing                      <M-P>
FileChooserToolbar                                
FileEditor.OpenDataEditor                         
FileMainSettingsGroup                             
FileMenu                                          
FileOpenGroup                                     
FileOtherSettingsGroup                            
FileSettingsGroup                                 
FileStructurePopup                                 <M-F12>
FillParagraph                                     
Find                                               <M-F>
FindInPath                                         <M-S-F>
FindMenuGroup                                     
FindModal                                          <C-F>
FindNext                                           <M-G>
FindPrevious                                       <M-S-G>
FindUsages                                         <A-F7> <C-F>
FindUsagesInFile                                   <M-F7>
FindWordAtCaret                                   
FixDocComment                                     
Flex.Debugger.FilterSwfLoadUnloadMessages         
Flex.NewActionScriptClass                         
Flex.NewFlexComponent                             
FoldingGroup                                      
ForceRunToCursor                                   <M-A-F9>
ForceStepInto                                      <A-S-F7>
ForceStepOver                                      <A-S-F8>
Forward                                            <M-A-Right> button=5 clickCount=1 modifiers=0 <C-S-=> <C-]>
FullyExpandTreeNode                                <j> <M-]>
Gant.NewScript                                    
Generate                                           <M-N>
Generate.Constructor.JavaScript                   
Generate.EventHandler.Actionscript                
Generate.GetAccessor.JavaScript                   
Generate.GetSetAccessor.JavaScript                
Generate.GrailsView                               
Generate.SetAccessor.JavaScript                   
Generate.SetUp.Actionscript                       
Generate.TearDown.Actionscript                    
Generate.TestMethod.Actionscript                  
Generate.ToString.Actionscript                    
GenerateAntBuild                                  
GenerateConstructor                               
GenerateCopyright                                 
GenerateCoverageReport                            
GenerateCreateUI                                  
GenerateDataMethod                                
GenerateDTD                                       
GenerateEJBFinderOrSelectorMethod                 
GenerateEJBReference                              
GenerateEntityListenerMethods                     
GenerateEquals                                    
GenerateExternalization                           
GenerateFilterAction                              
GenerateGetter                                    
GenerateGetterAndSetter                           
GenerateGroup                                     
GenerateInterceptorMethods                        
GenerateJavadoc                                   
GenerateJspFunctionAction                         
GenerateJspTagAction                              
GeneratePattern                                   
GeneratePersistenceContextReference               
GeneratePersistenceMapping                        
GenerateResourceReference                         
GenerateServletAction                             
GenerateSetter                                    
GenerateSetUpMethod                               
GenerateSuperMethodCall                           
GenerateTearDownMethod                            
GenerateTestMethod                                
GenerateXmlTag                                    
Generify                                          
Git.Add                                            <M-A-A> <C-G>
Git.Branches                                       <C-G>
Git.CheckoutRevision                              
Git.CompareWithBranch                             
Git.ContextMenu                                   
Git.CreateNewBranch                               
Git.CreateNewTag                                  
Git.Edit.Global.Message                           
Git.Fetch                                         
Git.Init                                          
Git.Log                                           
Git.Log.ContextMenu                               
Git.Log.DeepCompare                               
Git.Log.Toolbar                                   
Git.LogContextMenu                                
Git.Menu                                          
Git.Merge                                         
Git.Pull                                          
Git.Rebase                                        
Git.Rebase.Abort                                  
Git.Rebase.Continue                               
Git.Rebase.Skip                                   
Git.RepositoryContextMenu                         
Git.Reset                                         
Git.Reset.In.Log                                  
Git.ResolveConflicts                              
Git.Revert                                        
Git.Stash                                         
Git.Tag                                           
Git.Unstash                                       
GitFileActions                                    
Github.Create.Gist                                
Github.Create.Pull.Request                        
Github.Open.Commit.In.Browser                     
Github.Open.In.Browser                            
Github.Rebase                                     
Github.Share                                      
GitRepositoryActions                              
GlobalSettings                                    
Go.NewGoFile                                      
GoFmtFileAction                                    <M-A-S-F>
GoFmtProjectAction                                 <M-A-S-P>
GoGenerateBenchmark                               
GoGenerateTest                                    
GoImportsFileAction                               
GoShowTypeInternalAction                          
GoTestGenerateGroup                               
GotoAction                                         <M-S-A>
GotoBookmark0                                     
GotoBookmark1                                     
GotoBookmark2                                     
GotoBookmark3                                     
GotoBookmark4                                     
GotoBookmark5                                     
GotoBookmark6                                     
GotoBookmark7                                     
GotoBookmark8                                     
GotoBookmark9                                     
GotoChangedFile                                    <M-O>
GoToChangeMarkerGroup                             
GoToClass                                          <M-S-G>
GotoClass                                          <M-O>
GoToCodeGroup                                     
GotoCustomRegion                                   <M-A-.>
GotoDeclaration                                    <M-B> button=1 clickCount=1 modifiers=256 button=2 clickCount=1 modifiers=0
GoToEditPointGroup                                
GoToErrorGroup                                    
GotoFile                                           <M-S-O>
GotoImplementation                                 <M-A-B> button=1 clickCount=1 modifiers=768
GotoLine                                           <A-G>
GoToLinkTarget                                    
GoToMenu                                          
GoToMenuEx                                        
GotoNextBookmark                                  
GotoNextError                                      <F2>
GotoNextIncompletePropertyAction                   <F2>
GotoPreviousBookmark                              
GotoPreviousError                                  <S-F2>
GotoRelated                                        <M-C-Up>
GotoRow                                           
GotoSuperMethod                                    <M-U>
GotoSymbol                                         <M-A-O>
GoToTapestryClass                                 
GoToTapestryTemplate                              
GoToTargetEx                                      
GotoTest                                           <M-C-T>
GotoTypeDeclaration                                <M-S-B> <C-S-B> button=1 clickCount=1 modifiers=320 button=2 clickCount=1 modifiers=64
Gradle.AddGradleDslDependencyAction               
Gradle.ExecuteTask                                
Gradle.GenerateGroup                              
Gradle.ToggleOfflineAction                        
Grails                                            
Grails.Controller                                 
Grails.DomainClass                                
Grails.Filter                                     
Grails.GSP                                        
Grails.Script                                     
Grails.Service                                    
Grails.Shell                                      
Grails.TagLib                                     
Grails.UpdateDependencies                         
Grails.WAR                                        
Graph.ActualZoom                                  
Graph.CommonLayoutGroup                           
Graph.Current.Node.Dependencies.Filter            
Graph.DefaultGraphPopup                           
Graph.Delete                                       <Del> <BS> <M-BS>
Graph.ExportToFile                                
Graph.Faces.DefaultGraphPopup                     
Graph.Faces.OpenSelectedPages                      <M-Down> <F4>
Graph.FitContent                                  
Graph.Layout.BalloonLayouter                      
Graph.Layout.CircularLayouter                     
Graph.Layout.DirectedOrthogonalLayouter           
Graph.Layout.Fit.Content                          
Graph.Layout.HierarchicGroupLayouter              
Graph.Layout.OrganicLayouter                      
Graph.Layout.OrthogonalLayouter                   
Graph.Layout.TreeLayouter                         
Graph.Print                                       
Graph.Print.Preview                               
Graph.Show.Edge.Labels                            
Graph.ShowHideGrid                                
Graph.SnapToGrid                                  
Graph.ZoomIn                                       <k> <=>
Graph.ZoomOut                                      <m> <->
Griffon.UpdateDependencies                        
Groovy.Console                                    
Groovy.Doc.Generating                             
Groovy.Dynamic.CollapseAll                        
Groovy.Dynamic.ExpandAll                          
Groovy.Dynamic.Remove                             
Groovy.Dynamic.Toolbar                            
Groovy.NewClass                                   
Groovy.NewScript                                  
Groovy.Shell                                      
Groovy.Shell.Execute                               <M-CR>
GroovyGenerateGroup1                              
GuiceActionGroup                                  
GuiDesigner.AddComponent                          
GuiDesigner.AddGroup                              
GuiDesigner.AddTab                                
GuiDesigner.ChooseLocale                          
GuiDesigner.ComponentTreePopupMenu                
GuiDesigner.CreateComponent                        <M-N>
GuiDesigner.CreateListener                         <M-S-O>
GuiDesigner.DataBindingWizard                     
GuiDesigner.DecreaseIndent                         <S-Tab>
GuiDesigner.DeleteComponent                        <Del> <BS> <M-BS>
GuiDesigner.DeleteGroup                            <Del> <BS> <M-BS>
GuiDesigner.Duplicate                              <M-S-D>
GuiDesigner.EditComponent                          <F2>
GuiDesigner.EditGroup                              <F2>
GuiDesigner.EditorPopupMenu                       
GuiDesigner.ExpandSelection                        <A-Up> <M-Þ>
GuiDesigner.Flatten                               
GuiDesigner.FormSource                            
GuiDesigner.GenerateMain                          
GuiDesigner.GoToListener                           <M-A-B> button=1 clickCount=1 modifiers=768
GuiDesigner.GroupButtons                          
GuiDesigner.IncreaseIndent                         <Tab>
GuiDesigner.MainToolbarActions                    
GuiDesigner.Morph                                 
GuiDesigner.NewActions                            
GuiDesigner.Pack                                  
GuiDesigner.PaletteComponentPopupMenu             
GuiDesigner.PaletteGroupPopupMenu                 
GuiDesigner.PreviewForm                           
GuiDesigner.PropertyInspectorPopupMenu            
GuiDesigner.QuickJavadoc                           <C-J>
GuiDesigner.ReloadCustomComponents                
GuiDesigner.ResetValue                            
GuiDesigner.ShowComponentTags                     
GuiDesigner.ShowGrid                              
GuiDesigner.ShrinkSelection                        <A-Down> <M-S-Þ>
GuiDesigner.SurroundPopup                          <M-A-T>
GuiDesigner.UngroupButtons                        
GWT                                               
GWT.GenerateCompileReport                         
GWT.GenerateUiHandlerMethod                       
GWT.NewEntryPoint                                 
GWT.NewEventWithHandler                           
GWT.NewModule                                     
GWT.NewRemoteService                              
GWT.NewSerialClass                                
GWT.NewTestCase                                   
GWT.NewUiBinder                                   
Help.JetBrainsTV                                  
Help.KeymapReference                              
HelpMenu                                          
HelpTopics                                        
Heroku.RemoteServers.ShowContainerLog             
Heroku.RemoteServersViewPopup                     
Hg.Init                                           
Hg.Log.ContextMenu                                
Hg.Mq                                             
Hg.MQ.Unapplied                                   
hg4idea.branches                                  
hg4idea.CreateNewBranch                           
hg4idea.CreateNewTag                              
hg4idea.file.menu                                 
hg4idea.Graft.Continue                            
hg4idea.merge.files                               
hg4idea.mq.ShowUnAppliedPatches                   
hg4idea.pull                                      
hg4idea.QDelete                                    <Del> <BS> <M-BS>
hg4idea.QFinish                                   
hg4idea.QFold                                      <A-S-D>
hg4idea.QGoto                                     
hg4idea.QGotoFromPatches                           <A-S-G>
hg4idea.QImport                                   
hg4idea.QPushAction                                <A-S-P>
hg4idea.QRefresh                                   <M-R>
hg4idea.QRename                                   
hg4idea.Rebase.Abort                              
hg4idea.Rebase.Continue                           
hg4idea.resolve.mark                              
hg4idea.run.conflict.resolver                     
hg4idea.tag                                       
hg4idea.updateTo                                  
hg4idea.UpdateToRevision                          
Hibernate.SessionFactorySettings                  
HideActiveWindow                                   <S-Esc>
HideAllWindows                                     <M-S-F12>
HideCoverage                                      
HideSideWindows                                   
HierarchyGroup                                    
HighlightUsagesInFile                              <M-S-F7>
HippieBackwardCompletion                           <A-S-/>
HippieCompletion                                   <A-/>
Hotswap                                           
HtmlAddTableColumnAfter                           
HtmlAddTableColumnBefore                          
HtmlTableCellNavigateDown                          <M-A-S-Down>
HtmlTableCellNavigateLeft                          <M-A-S-Left>
HtmlTableCellNavigateRight                         <M-A-S-Right>
HtmlTableCellNavigateUp                            <M-A-S-Up>
I18nize                                           
IDEACoverageMenu                                  
IdeScriptingConsole                               
IgnoreChoicesGroup                                
Images.EditExternally                              <M-A-F4>
Images.Editor.ActualSize                           <M-o> <M-/>
Images.Editor.ToggleGrid                          
Images.Editor.ZoomIn                               <M-k> <M-]>
Images.Editor.ZoomOut                              <M-m> <M-->
Images.EditorPopupMenu                            
Images.EditorToolbar                              
Images.ShowThumbnails                              <M-C-T>
Images.Thumbnails.EnterAction                      <CR>
Images.Thumbnails.Hide                             <M-W>
Images.Thumbnails.ToggleRecursive                  <A-j>
Images.Thumbnails.UpFolder                         <BS>
Images.ThumbnailsPopupMenu                        
Images.ThumbnailsToolbar                          
Images.ToggleTransparencyChessboard               
ImplementMethods                                   <C-I>
ImportModule                                      
ImportModuleFromImlFile                           
ImportProject                                     
ImportSettings                                    
IncomingChanges.Refresh                           
IncomingChangesToolbar                            
IncrementalSearch                                 
IncrementWindowHeight                              <M-S-Down>
IncrementWindowWidth                               <M-S-Right>
InferNullity                                      
InheritanceToDelegation                           
Inline                                             <M-A-N>
InsertLiveTemplate                                 <M-J>
InspectCode                                       
InspectCodeGroup                                  
IntegrateChangeSetAction                          
IntegrateFiles                                    
IntroduceActionsGroup                             
IntroduceConstant                                  <M-A-C>
IntroduceField                                     <M-A-F>
IntroduceFunctionalParameter                      
IntroduceParameter                                 <M-A-P>
IntroduceParameterObject                          
IntroduceVariable                                  <M-A-V>
InvalidateCaches                                  
InvertBoolean                                     
J2EEGenerateGroup                                 
J2EEViewPopupMenu                                 
JasmineGenerateAfterEachMethodAction              
JasmineGenerateBeforeEachMethodAction             
JasmineGenerateNewSpecAction                      
JasmineGenerateNewSuiteAction                     
JavaCompileGroup                                  
JavaDebuggerActions                               
Javaee.Deploy                                     
Javaee.KeepDeployedAfterDisconnect                
Javaee.RefreshDeploymentStatus                    
Javaee.Undeploy                                   
javaee.UpdateRunningApplication                    <M-F10>
JavaeeEditorGenerateGroup                         
JavaeeMigrationGroup                              
JavaeeRunDeploymentViewToolbar                    
JavaeeRunToolWindowToolbar                        
JavaGenerateGroup1                                
JavaGenerateGroup2                                
JavaMethodHierarchyPopupMenu                      
Javascript.Linters.JSCS.Fix                       
JavaScriptDebugger.HideActionsGroup               
JavaScriptDebugger.HideDomPropertiesAction        
JavaScriptDebugger.OpenUrl                        
JAX-RS.GenerateJavaFromWADL                       
JAX-RS.GenerateWADL                               
JAXB                                              
Jdbc.OpenConsole                                   <M-S-F10>
Jdbc.OpenConsole.CreateNew                        
Jdbc.OpenTableEditor                               <M-Down> <F4>
Jdbc.RunQueryInConsole                             <M-CR>
Jdbc.RunQueryInConsole.Selection                  
Jdbc.RunSqlScript                                  <C-S-R>
jpa.AddJpaProviderSupport                         
Jpa.AssignDataSources                             
Jpa.OpenConsole                                    <M-S-F10>
JpaPatternAction                                  
JpaViewPopupMenu                                  
Jpdl.CreateJpdl                                   
Jpdl.Designer                                     
JS.TypeInfo                                       
JS.TypeScript.Compile                             
JS.TypeScript.Compile.Current                     
JSCallHierarchy.BaseOnThisMethod                  
JSCallHierarchyPopupMenu                          
JSClassHierarchyPopupMenu                         
JSHierarchyPopupMenu                              
JSMethodHierarchy.BaseOnThisMethod                
JSMethodHierarchyPopupMenu                        
JspActions                                        
JsTestFrameworkCodeGeneratorGroup                 
JumpToLastChange                                   <M-S-BS>
JumpToLastWindow                                   <F12>
JumpToNextChange                                  
LangCodeInsightActions                            
LanguageSpecificFoldingGroup                      
LegacyNewAndroidComponent                         
LocalHistory                                      
LocalHistory.PutLabel                             
LocalHistory.ShowHistory                          
LocalHistory.ShowSelectionHistory                 
LogDebugConfigure                                 
LookupActions                                     
Macros                                            
MacrosGroup                                       
MainMenu                                          
MaintenanceAction                                  <M-A-S-/>
MaintenanceGroup                                  
MainToolBar                                       
MainToolBarSettings                               
MakeAllJarsAction                                 
MakeJarAction                                     
MakeModule                                        
MakeStatic                                        
ManageProjectTemplatesAction                      
MarkAsOriginalTypeAction                          
MarkAsPlainTextAction                             
MarkExcludeRoot                                   
MarkFileAs                                        
MarkGeneratedSourceRoot                           
MarkGeneratedSourceRootGroup                      
MarkNotificationsAsRead                           
MarkRootGroup                                     
MarkSourceRootGroup                               
Maven.AddFileAsMavenProject                       
Maven.AddManagedFiles                             
Maven.AfterCompile                                
Maven.AfterRebuild                                
Maven.AlwaysShowArtifactId                        
Maven.AssignShortcut                              
Maven.BaseProjectMenu                             
Maven.BeforeCompile                               
Maven.BeforeRebuild                               
Maven.BeforeRun                                   
Maven.BuildMenu                                   
Maven.CollapseAll                                  <M-m> <M-->
Maven.DependencyGraphMenu                         
Maven.DependencyMenu                              
Maven.DownloadAllDocs                             
Maven.DownloadAllGroup                            
Maven.DownloadAllGroupPopup                       
Maven.DownloadAllSources                          
Maven.DownloadAllSourcesAndDocs                   
Maven.DownloadSelectedDocs                        
Maven.DownloadSelectedSources                     
Maven.DownloadSelectedSourcesAndDocs              
Maven.EditRunConfiguration                         <M-Down> <F4>
Maven.ExecuteGoal                                 
Maven.ExpandAll                                    <M-k> <M-]>
Maven.GenerateGroup                               
Maven.GlobalProjectMenu                           
Maven.GroupProjects                               
Maven.IgnoreProjects                              
Maven.NavigatorActionsToolbar                     
Maven.NavigatorProjectMenu                        
Maven.OpenProfilesXml                             
Maven.OpenSettingsXml                             
Maven.RefactoringGroup                            
Maven.Reimport                                    
Maven.ReimportProject                             
Maven.RemoveManagedFiles                          
Maven.RemoveRunConfiguration                       <Del> <BS> <M-BS>
Maven.RunBuild                                    
Maven.RunConfigurationMenu                        
Maven.ShowBasicPhasesOnly                         
Maven.ShowEffectivePom                            
Maven.ShowIgnored                                 
Maven.ShowSettings                                
Maven.ShowVersions                                
Maven.TasksGroup                                  
Maven.ToggleOffline                               
Maven.ToggleProfile                               
Maven.ToggleSkipTests                             
Maven.Uml.Exclude                                  <S-Del>
Maven.UpdateFolders                               
Maven.UpdateFoldersForProject                     
MaximizeToolWindow                                 <M-S-Þ>
MemberPushDown                                    
MembersPullUp                                     
MethodDown                                         <C-Down>
MethodDuplicates                                  
MethodHierarchy                                    <M-S-H>
MethodHierarchy.BaseOnThisType                    
MethodHierarchy.ImplementMethodAction              <C-I>
MethodHierarchy.OverrideMethodAction               <M-S-O>
MethodHierarchyPopupMenu                          
MethodUp                                           <C-Up>
Migrate                                           
MigrateCvsRoot                                    
MinimizeCurrentWindow                             
ModuleSettings                                    
Move                                               <F6>
MoveAttributeInAction                             
MoveAttributeOutAction                            
MoveEditorToOppositeTabGroup                      
MoveLineDown                                       <A-S-Down>
MoveLineUp                                         <A-S-Up>
MoveModuleToGroup                                 
MoveStatementDown                                  <M-S-Down>
MoveStatementUp                                    <M-S-Up>
MoveTabDown                                        <M-K>
MoveTabRight                                       <M-K>
Mq.Patches.ContextMenu                            
Mq.Patches.Toolbar                                
Mvc.Actions                                       
Mvc.Plugins                                       
Mvc.RunTarget                                      <M-A-G>
Mvc.Upgrade                                       
MyEditorPopupMenu                                 
NavbarPopupMenu                                   
NavBarToolBar                                     
NavBarToolBarOthers                               
NavBarVcsGroup                                    
NewAction                                         
NewAndroidAssetImage                              
NewApplicationComponent                           
NewCfmlFile                                       
NewClass                                          
NewCoffeeScriptFile                               
NewDialog                                         
NewDir                                            
NewElement                                         <M-N>
NewElementInMenuGroup                             
NewElementSamePlace                                <A-C-N>
NewFile                                           
NewForm                                           
NewFormSnapshot                                   
NewFromTemplate                                   
NewGroup                                          
NewGroup1                                         
NewGroupPersistence                               
NewGuiceBindingAnnotation                         
NewGuiceMethodInterceptor                         
NewGuiceModule                                    
NewGuiceProvider                                  
NewGuiceScopeAnnotation                           
NewHtmlFile                                       
NewJavaDiagram                                    
NewJavaScriptFile                                 
NewModule                                         
NewModuleComponent                                
NewModuleInGroup                                  
NewModulesDiagram                                 
NewPackageInfo                                    
NewProject                                        
NewProjectComponent                               
NewProjectFromVCS                                 
NewProjectOrModuleGroup                           
NewPropertyAction                                 
NewScratchFile                                     <M-S-N>
NewStylesheetFile                                 
NewTypeScriptFile                                 
NewXml                                            
NewXmlDescriptor                                  
NextDiff                                           <F7> <C-Down>
NextEditorTab                                      <C-S-Right>
NextOccurence                                      <M-A-Down>
NextParameter                                      <Tab>
NextProjectWindow                                  <M-À>
NextSplitter                                       <A-Tab>
NextTab                                            <M-S-]> <C-Right>
NextTemplateParameter                              <Tab>
NextTemplateVariable                               <Tab> <CR>
ObtainPermanentTicket                             
OnlineDocAction                                   
openAssertEqualsDiff                               <M-D>
OpenEditorInOppositeTabGroup                      
OpenEjbERDiagramAction                            
OpenFile                                          
OpenInBrowser                                     
OpenInBrowserEditorContextBarGroupAction          
OpenInBrowserGroup                                
OpenInSceneBuilder                                
OpenModuleSettings                                 <M-Down> <F4>
OpenPersistenceERDiagramAction                    
OpenProjectGroup                                  
OpenProjectWindows                                
OptimizeImports                                    <A-C-O>
org.jetbrains.plugins.groovy.actions.generate.accessors.GroovyGenerateGetterAction
org.jetbrains.plugins.groovy.actions.generate.accessors.GroovyGenerateGetterSetterAction
org.jetbrains.plugins.groovy.actions.generate.accessors.GroovyGenerateSetterAction
org.jetbrains.plugins.groovy.actions.generate.constructors.GroovyGenerateConstructorAction
org.jetbrains.plugins.groovy.actions.generate.equals.GroovyGenerateEqualsAction
org.jetbrains.plugins.groovy.actions.generate.missing.GroovyGenerateMethodMissingAction
org.jetbrains.plugins.groovy.actions.generate.missing.GroovyGeneratePropertyMissingAction
osgi.bnd.reimport                                 
osgi.bnd.reimport.all                             
osmorc.viewGeneratedManifests                     
OtherMenu                                         
OverrideMethods                                    <M-S-O>
PackageAIR                                        
PackageFile                                        <M-S-F9>
Pageflow.Designer                                 
PairFileActions                                   
ParameterInfo                                      <M-P>
PasteMultiple                                      <M-S-V>
Pause                                             
Perforce.Force.Refresh                            
PerforceDirect.Edit                                <M-A-E>
PerforceDirect.Menu                               
PerforceEnableIntegration                         
PinActiveTab                                      
PinToolwindowTab                                  
PlaybackLastMacro                                 
PlaySavedMacrosAction                             
PluginDeployActions                               
PopupHector                                        <M-A-S-H>
PowerSaveGroup                                    
PreviousDiff                                       <S-F7> <C-Up>
PreviousEditorTab                                  <C-S-Left>
PreviousOccurence                                  <M-A-Up>
PreviousProjectWindow                              <M-S-À>
PreviousTab                                        <M-S-[> <C-Left>
PreviousTemplateVariable                           <S-Tab>
PrevParameter                                      <S-Tab>
PrevSplitter                                       <A-S-Tab>
PrevTemplateParameter                              <S-Tab>
Print                                             
PrintExportGroup                                  
ProductivityGude                                  
ProfilingActions                                  
ProjectViewAnalysisGroup                          
ProjectViewChangeView                              <A-F1>
ProjectViewCompileGroup                           
ProjectViewPopupMenu                              
ProjectViewPopupMenuModifyGroup                   
ProjectViewPopupMenuRefactoringGroup              
ProjectViewPopupMenuRunGroup                      
ProjectViewPopupMenuSettingsGroup                 
PropertiesDiff                                    
PropertyInspectorActions                          
PropertyInspectorActions.AddProperty               <M-N>
PropertyInspectorActions.CommonActions            
PropertyInspectorActions.EditValue                 <CR>
PropertyInspectorActions.RemoveProperty            <Del> <BS> <M-BS>
PsiViewer                                         
PsiViewerForContext                               
PublishGroup                                      
PublishGroup.CompareLocalVsRemote                 
PublishGroup.Download                             
PublishGroup.SyncLocalVsRemote                    
PublishGroup.SyncLocalVsRemoteWith                
PublishGroup.Upload                               
PublishGroup.UploadTo                              <M-A-S-X>
PublishGroupPopupMenu                             
QuickActions                                      
QuickChangeScheme                                  <C-À>
QuickDocCopy                                       <M-C>
QuickEvaluateExpression                            <M-A-F8> button=1 clickCount=1 modifiers=512
QuickImplementations                               <M-Y>
QuickJavaDoc                                       <C-J>
QuickList.Deployment                              
QUnitGenerateNewTestAction                        
QUnitGenerateSetupAction                          
QUnitGenerateTearDownAction                       
RearrangeCode                                     
RecentChangedFiles                                 <M-S-E>
RecentChanges                                      <A-S-C>
RecentFiles                                        <M-E>
refactoring.extract.dependency                     <M-A-M>
refactoring.introduce.property                     <M-A-V>
RefactoringMenu                                   
RefactoringMenu1                                  
RefactoringMenu2                                  
RefactoringMenu4                                  
Refactorings.QuickListPopupAction                  <C-T>
ReformatCode                                       <M-A-L> <A-F>
Refresh                                            <M-R>
Register                                          
RegistrationActions                               
ReleasePermanentTicket                            
ReloadFromDisk                                    
RemoteExternalToolsGroup                          
RemoteHost.NewGroup                               
RemoteHost.NewRemoteItem                           <M-N>
RemoteHostView.CopyPaths                           <M-S-C>
RemoteHostView.CreateFile                         
RemoteHostView.CreateFolder                       
RemoteHostView.EditRemoteFile                     
RemoteHostView.EditSource                          <M-Down> <F4>
RemoteHostView.Rename                              <S-F6>
RemoteHostView.SetPermissions                     
RemoteHostView.ToggleExclusion                    
RemoteHostViewPopupMenu                           
RemoteServers.ChooseServerDeployment              
RemoteServers.ChooseServerDeploymentWithDebug     
RemoteServers.ConnectServer                       
RemoteServers.DisconnectServer                    
RemoteServers.EditDeploymentConfig                
RemoteServers.EditServerConfig                    
RemoteServersViewPopup                            
RemoteServersViewToolbar                          
RemoveFromFavorites                                <C-Del>
RemoveMiddleman                                   
RenameAttributeAction                             
RenameElement                                      <S-F6>
RenameFavoritesList                                <S-F6>
RenameFile                                        
RenameTagAction                                   
ReopenClosedTab                                    <M-S-T>
Replace                                            <M-R>
ReplaceAttributeWithTagAction                     
ReplaceConstructorWithBuilder                     
ReplaceConstructorWithFactory                     
ReplaceInPath                                      <M-S-R>
ReplaceMethodWithMethodObject                     
ReplaceTagWithAttributeAction                     
ReplaceTempWithQuery                              
RepositoryChangesBrowserToolbar                   
Rerun                                              <M-R>
RerunFailedTests                                  
RerunTests                                         <M-C-R> <A-S-R>
ResizeToolWindowDown                               <M-S-Down>
ResizeToolWindowGroup                             
ResizeToolWindowLeft                               <M-S-Left>
ResizeToolWindowRight                              <M-S-Right>
ResizeToolWindowUp                                 <M-S-Up>
Resolve                                           
ResolveAll                                        
REST                                              
RESTClient.RunRequest                             
RestoreDefaultLayout                               <S-F12>
Resume                                             <M-A-R>
RevealIn                                          
RevertUnchanged                                   
RevisionGraph                                     
Run                                                <M-A-S-R> <A-R>
RunClass                                           <C-S-R>
RunConfiguration                                  
RunContextGroup                                   
RunContextPopupGroup                              
RunCoverage                                       
RunGc                                             
RunInspection                                      <M-A-S-I>
RunJsbtTask                                        <A-F11>
RunMenu                                           
Runner.CloseAllUnpinnedViews                      
Runner.CloseAllViews                              
Runner.CloseOtherViews                            
Runner.CloseView                                  
Runner.Focus                                      
Runner.FocusOnStartup                             
Runner.Layout                                     
Runner.MinimizeView                               
Runner.RestoreLayout                              
Runner.View.Close.Group                           
Runner.View.Popup                                 
Runner.View.Toolbar                               
RunnerActions                                     
RunnerLayoutActions                               
RunTargetAction                                    <M-S-F10>
RunToCursor                                        <A-F9>
SafeDelete                                         <M-Del>
SaveAll                                            <M-S>
SaveAsNewFormat                                   
SaveAsTemplate                                    
SaveDocument                                      
SaveFileAsTemplate                                
SaveProjectAsTemplateAction                       
ScopeView.EditScopes                              
ScopeViewPopupMenu                                
ScrollTreeToCenter                                
Seam.Create.Components.Xml                        
Seam.Create.Pageflow                              
Seam.Create.Pages.Xml                             
SearchEverywhere                                  
SelectAllOccurrences                               <M-C-G>
SelectIn                                           <A-F1>
SelectInRemoteHost                                
SelectNextOccurrence                               <M-D>
SendEOF                                            <M-D>
SendFeedback                                      
SendToFavoritesGroup                              
Servers.Deploy                                    
Servers.DeployWithDebug                           
Servers.Undeploy                                  
ServersToolWindowToolbar                          
SetJobsForChangeList                              
SeverityEditorDialog                              
Shelve.KeymapGroup                                
ShelveChanges.UnshelveWithDialog                   <M-S-U>
ShelvedChanges.DeleteDeleted                      
ShelvedChanges.Diff                                <M-D>
ShelvedChanges.ImportPatches                      
ShelvedChanges.Rename                              <S-F6>
ShelvedChanges.Restore                            
ShelvedChanges.ShowHideDeleted                    
ShelvedChanges.Unshelve                           
ShelvedChangesPopupMenu                           
ShelvedChangesToolbar                             
ShelvedChangesToolbarGear                         
Show.Current.Revision                             
ShowAppliedStylesAction                           
ShowBackwardPackageDeps                           
ShowBookmarks                                      <M-F3>
ShowCdiDependenciesPopup                          
ShowColorPicker                                   
ShowContent                                        <C-Down>
ShowDependenciesOnTarget                          
ShowErrorDescription                               <M-F1>
ShowExecutionPoint                                 <A-F10>
ShowFilePath                                       <M-A-F12>
ShowIntentionActions                               <A-CR> <C-CR>
ShowJsbtTasks                                     
ShowLog                                           
ShowModulesDependencies                           
ShowNavBar                                         <M-Up> <A-Home>
ShowPackageCycles                                 
ShowPackageDeps                                   
ShowPackageDepsGroup                              
ShowPopupMenu                                     
ShowProcessWindow                                 
ShowProjectStructureSettings                       <M-;>
ShowPropertiesDiffVsLocal                         
ShowRecentFindUsagesGroup                         
ShowReformatFileDialog                            
ShowRegistry                                      
ShowSeamDependenciesGraph                         
ShowSettings                                       <M-,>
ShowSettingsAndFindUsages                          <M-A-S-F7>
ShowSiblings                                      
ShowTabsInSingleRow                               
ShowTips                                          
ShowUmlDiagram                                     <M-A-S-U>
ShowUmlDiagramPopup                                <M-A-U>
ShowUsages                                         <M-A-F7>
SliceBackward                                     
SliceForward                                      
SmartStepInto                                      <S-F7>
SmartTypeCompletion                                <C-S- >
SMTestRunnerStatistics                            
SMTestRunnerTestsTree                             
SplitHorizontally                                  <M-K>
SplitVertically                                    <M-K>
Spring.Beans.Generate.Action                      
Spring.Beans.Generate.Constructor.Dependency.Action
Spring.Beans.Generate.Setter.Dependency.Action    
Spring.Beans.Generate.Testing.Dependency.Action   
Spring.Create.Context.File                        
Spring.Patterns.ActionGroup                       
SpringGenerateGroup                               
Spy-js.AddLabel                                   
Spy-js.CaptureOnlyEvent                           
Spy-js.CaptureOnlyFile                            
Spy-js.CaptureOnlyStackFile                       
Spy-js.CloseDocument                              
Spy-js.CloseTraceFiles                            
Spy-js.Context.Tree                               
Spy-js.Event.Tree                                 
Spy-js.FileDependencyGraph.CommonLayoutGroup      
Spy-js.FileDependencyGraph.Default                
Spy-js.FileDependencyGraph.LocateEvent            
Spy-js.FileDependencyGraph.SearchFunction         
Spy-js.FileDependencyGraph.Tree                   
Spy-js.FindNextFunctionNextCallFromStack          
Spy-js.FindNextFunctionPreviousCallFromStack      
Spy-js.FindPrevFunctionNextCallFromStack          
Spy-js.FindPreviousFunctionPreviousCallFromStack  
Spy-js.FindThisFunctionNextCallFromStack          
Spy-js.FindThisFunctionPreviousCallFromStack      
Spy-js.GoToFirstFoundOccurence                    
Spy-js.GoToLastFoundOccurence                     
Spy-js.GoToNextFoundOccurence                     
Spy-js.GoToPreviousFoundOccurence                 
Spy-js.Graph.ExportToFile                         
Spy-js.Graph.Layout.Fit.Content                   
Spy-js.Graph.Preview                              
Spy-js.Graph.Print                                
Spy-js.Graph.Show.Edge.Labels                     
Spy-js.JumpToCaller                               
Spy-js.JumpToMappedTrace                          
Spy-js.JumpToPackageFile                          
Spy-js.JumpToSource                               
Spy-js.JumpToTrace                                
Spy-js.MuteEvent                                  
Spy-js.MuteFile                                   
Spy-js.MuteNodeModuleAction                       
Spy-js.MuteNodeModules                            
Spy-js.MuteStackFile                              
Spy-js.RefreshDocument                            
Spy-js.RemoveAndCloseTraceFiles                   
Spy-js.RemoveChildren                             
Spy-js.RemoveNode                                 
Spy-js.SearchFunction                             
Spy-js.SearchFunctionFromStack                    
Spy-js.ShowAppDependencyGraph                     
Spy-js.ShowEventDependencyGraph                   
Spy-js.Stack.Toolbar                              
Spy-js.Stack.Tree                                 
sql.ChangeDialectAction                           
SqlGenerateGroup                                  
StandardMacroActions                              
Start.Use.Vcs                                     
StartStopMacroRecording                           
StartupWizard                                     
StepInto                                           <F7>
StepOut                                            <S-F8>
StepOver                                           <F8>
Stop                                               <M-F2>
StoreDefaultLayout                                
StructuralSearchActions                           
StructuralSearchPlugin.StructuralReplaceAction    
StructuralSearchPlugin.StructuralSearchAction     
StructureViewCompileGroup                         
StructureViewPopupMenu                            
Struts.Generate.Actions.Group                     
Struts2.Create.StrutsXml                          
Subversion.BrowseSVNRepository                    
Subversion.CleanupProject                         
Subversion.Clenaup                                
Subversion.CompareWithBranch                      
Subversion.Copy                                   
Subversion.Create.External                        
Subversion.ImportToSVNRepository                  
Subversion.Lock                                   
Subversion.MarkLocallyDeletedTreeResolved         
Subversion.MarkResolved                           
Subversion.MarkTreeResolved                       
Subversion.MergeFrom                              
Subversion.Relocate                               
Subversion.Resolve                                
Subversion.SetProperty                            
Subversion.Share                                  
Subversion.ShareWholeProject                      
Subversion.ShowProperties                         
Subversion.TogglePropertiesDiff                   
Subversion.Unlock                                 
SubversionFilePopupGroup                          
SubversionGroup                                   
SubversionUpdateActionGroup                       
SurroundWith                                       <M-A-T>
SurroundWithEmmet                                 
SurroundWithLiveTemplate                           <M-A-J>
SwitchApply                                        <A-C-CR>
SwitchBootJdk                                     
SwitchCoverage                                     <M-A-F6>
SwitchDown                                         <A-C-Down>
Switcher                                           <C-Tab> <C-S-Tab>
SwitchLeft                                         <A-C-Left>
SwitchRight                                        <A-C-Right>
SwitchUp                                           <A-C-Up>
SwitchViewActions                                 
Synchronize                                        <M-A-Y>
SynchronizeCurrentFile                            
TabList                                           
TabsAlphabeticalMode                              
TabsPlacementBottom                               
TabsPlacementGroup                                
TabsPlacementLeft                                 
TabsPlacementNone                                 
TabsPlacementRight                                
TabsPlacementTop                                  
TagDocumentationNavigation                         <M-S-D>
TalkToFdb.Flex.Debug                              
TapestryGroup                                     
task.actions                                      
tasks.analyze.stacktrace                          
tasks.and.contexts                                
tasks.close                                        <A-S-W>
tasks.configure.servers                           
tasks.create.changelist                           
tasks.goto                                         <A-S-N>
tasks.group                                       
tasks.open.in.browser                              <A-S-B>
tasks.show.task.description                       
tasks.switch                                       <A-S-T>
tasks.switch.toolbar                               <A-S-T>
tasks.toolbar.group                               
TechnicalSupport                                  
TemplateParametersNavigation                      
TemplateProjectProperties                          <M-;>
TemplateProjectSettingsGroup                      
TemplateProjectStructure                           <A-;>
TestData.Navigate                                  <M-C-Up>
Testing.SelectInTree                              
TestStatisticsTablePopupMenu                      
TestTreePopupMenu                                 
TextComponent.ClearAction                          <Esc>
Tfs.Add                                           
Tfs.Branch                                        
Tfs.Checkout                                      
TFS.CreateVirtualFolder                           
Tfs.ItemInfo                                      
Tfs.Label                                         
Tfs.Lock                                          
TFS.ManageWorkspaces                              
Tfs.MergeChanges                                  
TfsFilePopupGroup                                 
TfsGlobalGroup                                    
TfsGroup                                          
TfsTreePopupMenu                                  
TimeLapseView                                     
ToggleBookmark                                     <F3>
ToggleBookmark0                                   
ToggleBookmark1                                   
ToggleBookmark2                                   
ToggleBookmark3                                   
ToggleBookmark4                                   
ToggleBookmark5                                   
ToggleBookmark6                                   
ToggleBookmark7                                   
ToggleBookmark8                                   
ToggleBookmark9                                   
ToggleBookmarkWithMnemonic                         <A-F3>
ToggleBreakpointAction                            
ToggleBreakpointEnabled                           
ToggleContentUiTypeMode                           
ToggleDistractionFreeMode                         
ToggleDockMode                                    
ToggleFieldBreakpoint                             
ToggleFloatingMode                                
ToggleFullScreen                                   <M-C-F>
ToggleFullScreenGroup                             
ToggleLineBreakpoint                               <M-F8>
ToggleMethodBreakpoint                            
TogglePinnedMode                                  
TogglePopupHints                                  
TogglePowerSave                                   
TogglePresentationMode                            
ToggleReadOnlyAttribute                           
ToggleSideMode                                    
ToggleTemporaryLineBreakpoint                      <M-A-S-F8>
ToggleWindowedMode                                
ToolbarFindGroup                                  
ToolbarMakeGroup                                  
ToolbarRunGroup                                   
ToolsBasicGroup                                   
ToolsMenu                                         
ToolsXmlGroup                                     
ToolWindowsGroup                                  
TurnRefsToSuper                                   
TypeHierarchy                                     
TypeHierarchy.BaseOnThisType                      
TypeHierarchy.Class                               
TypeHierarchy.Subtypes                            
TypeHierarchy.Supertypes                          
TypeHierarchyBase.BaseOnThisType                  
TypeHierarchyPopupMenu                            
UiDebugger                                        
UIToggleActions                                   
UML.ActualSize                                    
Uml.Analyze                                       
UML.ApplyCurrentLayout                             <F5>
Uml.CollapseNodes                                 
UML.DefaultGraphPopup                             
UML.EditorGroup                                   
Uml.ExpandNodes                                   
UML.ExportToFile                                  
UML.Find                                          
UML.FitContent                                    
UML.Group                                         
UML.Group.Simple                                  
Uml.NewElement                                    
Uml.NewGroup                                      
Uml.NodeCellEditorPopup                           
Uml.NodeIntentions                                
UML.PrintGraph                                    
UML.PrintPreview                                  
Uml.PsiElement.Actions                            
Uml.Refactoring                                   
UML.SaveDiagram                                   
UML.ShowChanges                                    <M-A-S-D>
Uml.ShowDiff                                      
UML.ShowStructure                                 
Uml.Standard.Toolbar.Actions                      
UML.ZoomIn                                        
UML.ZoomOut                                       
UnmarkGeneratedSourceRoot                         
UnmarkRoot                                        
Unscramble                                        
UnselectPreviousOccurrence                         <C-S-G>
Unsplit                                            <M-K>
UnsplitAll                                         <M-K>
Unversioned.Files.Dialog                          
Unwrap                                             <M-S-Del>
UnwrapTagAction                                   
UpdateActionGroup                                 
UpdateCopyright                                   
UpdateFiles                                       
UsageView.Exclude                                  <Del> <BS> <M-BS>
UsageView.Include                                  <S-BS>
UsageView.Popup                                   
UsageView.Rerun                                    <M-R>
UsageView.ShowRecentFindUsages                     <M-E>
vaadin.CreateCustomComponent                      
vaadin.CreateWidget                               
ValidateJsp                                       
ValidateXml                                       
Vcs.Browse                                        
Vcs.ChangesView                                   
Vcs.CheckCommitMessageSpelling                    
Vcs.CheckinProjectPopup                           
Vcs.CheckinProjectToolbar                         
Vcs.Checkout                                      
Vcs.CherryPick                                    
Vcs.CopyRevisionNumberAction                      
Vcs.History                                       
Vcs.Import                                        
Vcs.IntegrateProject                              
Vcs.KeymapGroup                                   
Vcs.Log.ContextMenu                               
Vcs.Log.CreatePatch                               
Vcs.Log.GoToRef                                    <M-F>
Vcs.Log.IntelliSortChooser                        
Vcs.Log.QuickSettings                             
Vcs.Log.Toolbar                                   
Vcs.MessageActionGroup                            
Vcs.Push                                           <M-S-K> <C-G>
Vcs.QuickListPopupAction                           <C-V>
Vcs.RefreshStatuses                               
Vcs.RollbackChangedLines                           <M-A-Z>
Vcs.ShowDiffWithLocal                             
Vcs.ShowHistoryForBlock                           
Vcs.ShowMessageHistory                             <M-E>
Vcs.ShowTabbedFileHistory                         
Vcs.Specific                                      
Vcs.UpdateProject                                  <M-T>
VcsFileGroupPopup                                 
VcsGeneral.KeymapGroup                            
VcsGlobalGroup                                    
VcsGroup                                          
VcsGroups                                         
VcsHistory.ShowAllAffected                         <M-C-A>
VcsHistoryActionsGroup                            
VcsNavBarToobarActions                            
VcsShowCurrentChangeMarker                        
VcsShowNextChangeMarker                            <A-C-S-Down>
VcsShowPrevChangeMarker                            <A-C-S-Up>
VcsToobarActions                                  
VersionControlsGroup                              
ViewBreakpoints                                    <M-S-F8>
ViewImportPopups                                  
ViewMenu                                          
ViewNavigationBar                                 
ViewOfflineInspection                             
ViewRecentActions                                 
ViewSource                                         <M-CR>
ViewStatusBar                                     
ViewToolBar                                       
ViewToolButtons                                   
VimAutoIndentLines                                
VimAutoIndentVisual                               
VimBack                                           
VimCancelExEntry                                  
VimChangeCaseLowerMotion                          
VimChangeCaseLowerVisual                          
VimChangeCaseToggleCharacter                      
VimChangeCaseToggleMotion                         
VimChangeCaseToggleVisual                         
VimChangeCaseUpperMotion                          
VimChangeCaseUpperVisual                          
VimChangeCharacter                                
VimChangeCharacters                               
VimChangeEndOfLine                                
VimChangeLine                                     
VimChangeMotion                                   
VimChangeNumberDec                                
VimChangeNumberInc                                
VimChangeReplace                                  
VimChangeVisual                                   
VimChangeVisualCharacter                          
VimChangeVisualLines                              
VimChangeVisualLinesEnd                           
VimCopyPutTextAfterCursor                         
VimCopyPutTextAfterCursorMoveCursor               
VimCopyPutTextAfterCursorNoIndent                 
VimCopyPutTextBeforeCursor                        
VimCopyPutTextBeforeCursorMoveCursor              
VimCopyPutTextBeforeCursorNoIndent                
VimCopySelectRegister                             
VimCopyYankLine                                   
VimCopyYankMotion                                 
VimCopyYankVisual                                 
VimCopyYankVisualLines                            
VimDeleteCharacter                                
VimDeleteCharacterLeft                            
VimDeleteCharacterRight                           
VimDeleteEndOfLine                                
VimDeleteJoinLines                                
VimDeleteJoinLinesSpaces                          
VimDeleteJoinVisualLines                          
VimDeleteJoinVisualLinesSpaces                    
VimDeleteLine                                     
VimDeleteMotion                                   
VimDeleteVisual                                   
VimDeleteVisualLines                              
VimDeleteVisualLinesEnd                           
VimExBackspace                                    
VimExEntry                                        
VimFileGetAscii                                   
VimFileGetFileInfo                                
VimFileGetHex                                     
VimFileGetLocationInfo                            
VimFilePrevious                                   
VimFileSaveClose                                  
VimFilterCountLines                               
VimFilterMotion                                   
VimFilterVisualLines                              
VimForward                                        
VimGotoDeclaration                                
VimInsertAfterCursor                              
VimInsertAfterLineEnd                             
VimInsertAtPreviousInsert                         
VimInsertBeforeCursor                             
VimInsertBeforeFirstNonBlank                      
VimInsertCharacterAboveCursor                     
VimInsertCharacterBelowCursor                     
VimInsertDeleteInsertedText                       
VimInsertDeletePreviousWord                       
VimInsertEnter                                    
VimInsertExitMode                                 
VimInsertLineStart                                
VimInsertNewLineAbove                             
VimInsertNewLineBelow                             
VimInsertPreviousInsert                           
VimInsertPreviousInsertExit                       
VimInsertRegister                                 
VimInsertReplaceToggle                            
VimInsertSingleCommand                            
VimLastGlobalSearchReplace                        
VimLastSearchReplace                              
VimMotionBigWordEndLeft                           
VimMotionBigWordEndRight                          
VimMotionBigWordLeft                              
VimMotionBigWordRight                             
VimMotionCamelEndLeft                             
VimMotionCamelEndRight                            
VimMotionCamelLeft                                
VimMotionCamelRight                               
VimMotionColumn                                   
VimMotionDown                                     
VimMotionDownFirstNonSpace                        
VimMotionDownLess1FirstNonSpace                   
VimMotionFirstColumn                              
VimMotionFirstNonSpace                            
VimMotionFirstScreenColumn                        
VimMotionFirstScreenLine                          
VimMotionFirstScreenNonSpace                      
VimMotionGotoFileMark                             
VimMotionGotoFileMarkLine                         
VimMotionGotoLineFirst                            
VimMotionGotoLineLast                             
VimMotionGotoLineLastEnd                          
VimMotionGotoMark                                 
VimMotionGotoMarkLine                             
VimMotionInnerBlockAngle                          
VimMotionInnerBlockBackQuote                      
VimMotionInnerBlockBrace                          
VimMotionInnerBlockBracket                        
VimMotionInnerBlockDoubleQuote                    
VimMotionInnerBlockParen                          
VimMotionInnerBlockSingleQuote                    
VimMotionInnerParagraph                           
VimMotionInnerSentence                            
VimMotionJumpNext                                 
VimMotionJumpPrevious                             
VimMotionLastColumn                               
VimMotionLastMatchChar                            
VimMotionLastMatchCharReverse                     
VimMotionLastNonSpace                             
VimMotionLastScreenColumn                         
VimMotionLastScreenLine                           
VimMotionLeft                                     
VimMotionLeftMatchChar                            
VimMotionLeftTillMatchChar                        
VimMotionLeftWrap                                 
VimMotionMark                                     
VimMotionMethodBackwardEnd                        
VimMotionMethodBackwardStart                      
VimMotionMethodForwardEnd                         
VimMotionMethodForwardStart                       
VimMotionMiddleColumn                             
VimMotionMiddleScreenLine                         
VimMotionNextTab                                  
VimMotionNthCharacter                             
VimMotionOuterBlockAngle                          
VimMotionOuterBlockBackQuote                      
VimMotionOuterBlockBrace                          
VimMotionOuterBlockBracket                        
VimMotionOuterBlockDoubleQuote                    
VimMotionOuterBlockParen                          
VimMotionOuterBlockSingleQuote                    
VimMotionOuterParagraph                           
VimMotionOuterSentence                            
VimMotionParagraphNext                            
VimMotionParagraphPrevious                        
VimMotionPercentOrMatch                           
VimMotionPreviousTab                              
VimMotionRight                                    
VimMotionRightMatchChar                           
VimMotionRightTillMatchChar                       
VimMotionRightWrap                                
VimMotionScrollColumnLeft                         
VimMotionScrollColumnRight                        
VimMotionScrollFirstScreenColumn                  
VimMotionScrollFirstScreenLine                    
VimMotionScrollFirstScreenLinePageStart           
VimMotionScrollFirstScreenLineStart               
VimMotionScrollHalfPageDown                       
VimMotionScrollHalfPageUp                         
VimMotionScrollLastScreenColumn                   
VimMotionScrollLastScreenLine                     
VimMotionScrollLastScreenLinePageStart            
VimMotionScrollLastScreenLineStart                
VimMotionScrollLineDown                           
VimMotionScrollLineUp                             
VimMotionScrollMiddleScreenLine                   
VimMotionScrollMiddleScreenLineStart              
VimMotionScrollPageDown                           
VimMotionScrollPageUp                             
VimMotionSectionBackwardEnd                       
VimMotionSectionBackwardStart                     
VimMotionSectionForwardEnd                        
VimMotionSectionForwardStart                      
VimMotionSentenceEndNext                          
VimMotionSentenceEndPrevious                      
VimMotionSentenceStartNext                        
VimMotionSentenceStartPrevious                    
VimMotionTextInnerBigWord                         
VimMotionTextInnerWord                            
VimMotionTextOuterBigWord                         
VimMotionTextOuterWord                            
VimMotionUnmatchedBraceClose                      
VimMotionUnmatchedBraceOpen                       
VimMotionUnmatchedParenClose                      
VimMotionUnmatchedParenOpen                       
VimMotionUp                                       
VimMotionUpFirstNonSpace                          
VimMotionWordEndLeft                              
VimMotionWordEndRight                             
VimMotionWordLeft                                 
VimMotionWordRight                                
VimPlaybackLastRegister                           
VimPlaybackRegister                               
VimPluginToggle                                    <M-A-V>
VimProcessExEntry                                 
VimProcessExKey                                   
VimRedo                                           
VimReformatVisual                                 
VimRepeatChange                                   
VimRepeatExCommand                                
VimResetMode                                      
VimSearchAgainNext                                
VimSearchAgainPrevious                            
VimSearchFwdEntry                                 
VimSearchRevEntry                                 
VimSearchWholeWordBackward                        
VimSearchWholeWordForward                         
VimSearchWordBackward                             
VimSearchWordForward                              
VimShiftLeftLines                                 
VimShiftLeftMotion                                
VimShiftLeftVisual                                
VimShiftRightLines                                
VimShiftRightMotion                               
VimShiftRightVisual                               
VimShortcutKeyAction                               <Del> <C-Ȁ> <C-U> <S-à> <C-V> <S-á> <C-A> <S-â> <BS> <C-Ȃ> <C-B> <C-W> <S-ã> <CR> <C-X> <Tab> <C-C> <C-S-2> <S-Left> <ￋ> <C-D> <C-Y> <S-Up> <S-Right> <C-E> <S-Down> <C-F> <C-[> <S-Tab> <C-\> <C-2> <C-G> <C-H> <C-]> <Esc> <Ins> <C-S-6> <C-I> <à> <â> <C-à> <Pagedown> <á> <Pageup> <Home> <End> <ã> <Up> <Left> <C-á> <Down> <C-â> <Right> <C-M> <C-N> <C-End> <C-ã> <C-Home> <C-O> <C-P> <C-Left> <C-Up> <C-Q> <C-R> <C-Right> <C-Down> <C-S> <C-T>
VimToggleRecording                                
VimUndo                                           
VimVisualBlockAppend                              
VimVisualBlockInsert                              
VimVisualExitMode                                 
VimVisualPutText                                  
VimVisualPutTextMoveCursor                        
VimVisualPutTextNoIndent                          
VimVisualSelectPrevious                           
VimVisualSwapEnds                                 
VimVisualSwapEndsBlock                            
VimVisualSwapSelections                           
VimVisualToggleBlockMode                          
VimVisualToggleCharacterMode                      
VimVisualToggleLineMode                           
VimWindowClose                                    
VimWindowDown                                     
VimWindowLeft                                     
VimWindowNext                                     
VimWindowOnly                                     
VimWindowPrev                                     
VimWindowRight                                    
VimWindowSplitHorizontal                          
VimWindowSplitVertical                            
VimWindowUp                                       
VisualizeSourceMap                                
WD.UploadCurrentRemoteFileAction                   <A-S-Q>
WebDeployment.BrowseServers                       
WebDeployment.Configuration                       
WebDeployment.Options                             
WebDeployment.ToggleAutoUpload                    
Webflow.Create.Context.File                       
WebOpenInAction                                    <A-F2>
WebResourcesGroup                                 
WebServicesActions                                
WebServicesPlugin.CreateRESTClient                
WebServicesPlugin.CreateRestfulWebService         
WebServicesPlugin.CreateRestfulWebServiceClient   
WebServicesPlugin.CreateWebService                
WebServicesPlugin.CreateWebServiceClient          
WebServicesPlugin.GenerateJavaFromJAXBSchemas     
WebServicesPlugin.GenerateJavaFromWsdl            
WebServicesPlugin.GenerateJavaFromXmlBeansSchemas 
WebServicesPlugin.GenerateJAXBSchemasFromJava     
WebServicesPlugin.GenerateWsdlFromJava            
WebServicesPlugin.MonitorSoapMessages             
WebServicesPlugin.ShowDeployedWebServices         
WeighingNewGroup                                  
WelcomeScreen.ChangeProjectIcon                   
WelcomeScreen.Configure                           
WelcomeScreen.Configure.DesktopEntry              
WelcomeScreen.Configure.Export                    
WelcomeScreen.Configure.IDEA                      
WelcomeScreen.Configure.Import                    
WelcomeScreen.CreateNewProject                    
WelcomeScreen.CreateWebProject                    
WelcomeScreen.DevelopPlugins                      
WelcomeScreen.Documentation                       
WelcomeScreen.Documentation.IDEA                  
WelcomeScreen.EditGroup                           
WelcomeScreen.GetFromVcs                          
WelcomeScreen.ImportProject                       
WelcomeScreen.MoveToGroup                         
WelcomeScreen.NewGroup                            
WelcomeScreen.OpenProject                         
WelcomeScreen.OpenSelected                        
WelcomeScreen.Plugins                             
WelcomeScreen.QuickStart                          
WelcomeScreen.QuickStart.IDEA                     
WelcomeScreen.Register                            
WelcomeScreen.RemoveSelected                      
WelcomeScreen.Settings                            
WelcomeScreen.Update                              
WelcomeScreenRecentProjectActionGroup             
WhatsNewAction                                    
WindowMenu                                        
working.context                                   
WrapReturnValue                                   
WrapTagAction                                     
WrapTagContentsAction                             
XDebugger.Actions                                 
XDebugger.CompareValueWithClipboard               
XDebugger.CopyName                                
XDebugger.CopyValue                               
XDebugger.CopyWatch                               
XDebugger.EditWatch                               
XDebugger.Evaluation.Dialog.Tree.Popup            
XDebugger.Frames.TopToolbar                       
XDebugger.Frames.Tree.Popup                       
XDebugger.Inline                                  
XDebugger.Inspect                                 
XDebugger.Inspect.Tree.Popup                      
XDebugger.JumpToSource                            
XDebugger.JumpToTypeSource                        
XDebugger.MuteBreakpoints                         
XDebugger.NewWatch                                
XDebugger.RemoveAllWatches                        
XDebugger.RemoveWatch                             
XDebugger.Settings                                
XDebugger.SetValue                                
XDebugger.ToggleSortValues                        
XDebugger.ToolWindow.LeftToolbar                  
XDebugger.ToolWindow.TopToolbar                   
XDebugger.UnmuteOnStop                            
XDebugger.ValueGroup                              
XDebugger.ValueGroup.CopyJson                     
XDebugger.Variables.Tree.Popup                    
XDebugger.Variables.Tree.Toolbar                  
XDebugger.Watches.Tree.Popup                      
XDebugger.Watches.Tree.Toolbar                    
XmlBeans                                          
XmlGenerateToolsGroup                             
XMLRefactoringMenu                                
XPathView.Actions.Evaluate                         <M-A-X>
XPathView.Actions.FindByExpression                 <M-A-X>
XPathView.Actions.ShowPath                         <M-A-X>
XPathView.EditorPopup                             
XPathView.MainMenu.Search                         
XPathView.XSLT.Associations                       
XSD2Document                                      
ZoomCurrentWindow                                  <M-C-=>
